### ISSUE TITLE
basic_claim missing as_object

### ISSUE THREAD

**Issue by ALTinners** [Thalhammer/jwt-cpp#101]
Just reading through the header for `basic_claim` and can see there is no `as_object()` to match the `as_string()`, `as_array()` and other similar functions

Not good with the standard by any means - but from the spec

> For JWTs, while claim names are strings, claim values can be any JSON type

Of which an `object` should be fine. Is there a reason for `as_object` to be omitted or is this an oversight? 

I can make a pull if its an oversight

**Comment by prince-chrismc** [comment]
oversight would be possible. I think it simply was not required to handle the JWTs structure, signing or verification.

I am certainly in favor of this. Please open a PR.

It's possible to use `to_json()` as an alternative.

**Comment by prince-chrismc** [comment]
Closing as resolved
