### ISSUE TITLE
Check Expiration without verifying Algorithm?

### ISSUE THREAD

**Issue by FohlenAFK** [Thalhammer/jwt-cpp#110]
Hello @Thalhammer,

Thanks for implementing the jwt-cpp library. I'm having a problem because I can't get a key from the application to check the JWT. So I have to assume that this is okay.
Is it possible to check the "exp" without verifying the algorithm or do I have to do it manually?

 It seems the `verify` function requires the algorithm:
https://github.com/Thalhammer/jwt-cpp/blob/f85e6dfe9034c32c09e96e0df6017891ff55b49c/include/jwt-cpp/jwt.h#L2515

The header of the given JWT contains:
```
{
  "alg":"RS256",
  "typ" : "JWT",
  "kid" : "QcypehCuxrEzRu6gR1j3KHPh94vIp7zlry3px5hZ313"
}"
```

**Comment by Thalhammer** [comment]
Hi,

You can use decoded_jwt for this.
It has member variables to check if exp is present and to get it (same for iat and nbf).
Instanciating decoded_jwt does not need a key, as it only decodes it and does not verify anything (apart from basic integrity).
All of them return a "date" which is just a typedef for `std::chrono::system_clock::time_point`, so you can compare them with the current system clock.
iat and nbf should be less then now() and exp should be more than now().  You should probably allow some leeway in case your (or the creating parties) clock is not 100% accurate.
However be warned that I do not recommend this for anything that has to do with security as **anyone** could create a token that passes this test with basically zero effort.

**Comment by FohlenAFK** [comment]
Okay, so I have to check it myself. Thanks for your quick reply 👍 

> However be warned that I do not recommend this for anything that has to do with security as anyone could create a token that passes this test with basically zero effort.

Yes, that's clear. I think the application uses this type of token only because it is possible to define a lifetime. 🤦
