### ISSUE TITLE
Can I use this library to encrypt/decode string

### ISSUE THREAD

**Issue by laoshanxi** [Thalhammer/jwt-cpp#115]
Can I use this library to encrypt/decode string instead of introduce other encrypt lib?

**Comment by Thalhammer** [comment]
No. The Library does not implement anything related to cryptography. It relies on either openssl or libressl to do the actual crypto. So if you use this library you are already using one of those, which do implement various encryption and decryption functions. If you dont use this library you'll have to either directly use one of those two or link to a different cryptography library. That said I'd recommend sticking to either openssl or libressl as they are the defacto standard for crypto and at least one of them will be present on pretty much every system you'll ever encounter.

**Comment by laoshanxi** [comment]
Thanks you for the reply!

I am using this library in [app-mesh](https://github.com/laoshanxi/app-mesh) and this is really very good. so I am considering whether I can use this similar approach for string encrypt.

For use openssl or libressl, that's much deep level and I am not familiar with that, but with this JWT token, it seems the token is too long for some short string.

Is there any other simple way to encrypt and decode string without explicit a secret key?

**Comment by prince-chrismc** [comment]
### Are you trying to protect data?

Common example is a password, personal information, backing details, etc.

If yes, JWT are **not the right answer**! All the data is available in "plain text".

> A JWT can be used to:
Propagate one’s identity between interested parties.
Propagate user entitlements between interested parties.
Transfer data securely between interested parties over a unsecured channel.
Assert one’s identity, given that the recipient of the JWT trusts the asserting party.

[ref](https://medium.facilelogin.com/jwt-jws-and-jwe-for-not-so-dummies-b63310d201a3)

---

You might want to take a look at https://wiki.openssl.org/index.php/EVP_Symmetric_Encryption_and_Decryption which is a create starting place. As for a library, I have seen https://github.com/weidai11/cryptopp, which might help you in ur search.

PS cool project and we are glad to hear you had a great experience with our project!

**Comment by mohsenomidi** [comment]
My personal favorite is [Botan crypto library](https://github.com/randombit/botan) and it is C++ implementation of cryptography, easy to use much mor control as you want, and well documented.

**Comment by laoshanxi** [comment]
Thanks @mohsenomidi  @prince-chrismc for the guidance. I will try those libraries.
Merry Christmas!

**Comment by prince-chrismc** [comment]
🎄
