### ISSUE TITLE
std::bad_cast for one audience case

### ISSUE THREAD

**Issue by pbludov** [Thalhammer/jwt-cpp#13]
According to the [spec](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-25#section-4.1.3),

> In the  special case when the JWT has one audience, the `aud` value *MAY* be a
   single case-sensitive string containing a StringOrURI value.

so, the `aud` claim may be either a string or an array of strings.

**Comment by Thalhammer** [comment]
Should be an easy fix, will change and push it once home and on a computer.

**Comment by pbludov** [comment]
Thank you very much!

Could you, please, add overload `jwt::builder::set_audience(const std::string& str)` as well?

**Comment by Thalhammer** [comment]
@pbludov Yeah sure but you can also simply write set_audience({str})
