### ISSUE TITLE
Can we load verifier once, and use same for multiple message token  verification  instead of creating new object each time

### ISSUE THREAD

**Issue by akanksha23new** [Thalhammer/jwt-cpp#130]
Hi,

Thanks for the library, i am fairly new to this. 
Able to run it using examples. However, need help as i have multiple messages incoming which need verification using same verifier, which i want to be loaded once at startup.

Since using auto unable to define default verifier class object which could be initialised later at startup.

Tried using the provided constructor: 
`explicit verifier(Clock )`

verifier instance in .h file:
`jwt::verifier<jwt::default_clock, jwt::picojson_traits> messageValidator_(jwt::default_clock);`

Initialising same by reading config of application on startup once :
`messageValidator_ = jwt::verify().allow_algorithm(jwt::algorithm::rs256(pub_key, "", "", "")).with_audience(audience);`

Using this object messageValidator_ each time message comes in  :   
`messageValidator_.verify(decode);`

This doesn't Compiles, unable to figure this. Really appreciate some help or some correction in case wrong.
Thanks.

**Comment by prince-chrismc** [comment]
Can you please provide OS, Compiler (and version) along with the error you are getting?

Also since you are using the `picojson_traits` you can skip the template specialization.

Have you tried this?
https://github.com/Thalhammer/jwt-cpp/blob/5b20cd637aa2760812c544bb2cf20087d0a01ec7/example/rsa-verify.cpp#L52-L57

***

I suspect there a small typo in your code that causing you grief. 

> ⚠️ I did not try compiling but this might be an example.

- Header
```cpp
class my_verification {
   jwt::verifier<jwt::default_clock, jwt::picojson_traits> messageValidator_ { default_clock{} };

   my_verification();
}
```

- Source
```cpp
my_verification::my_verification() {
   messageValidator_.allow_algorithm(jwt::algorithm::rs256(pub_key, "", "", "")).with_audience(audience);
}
```

**Comment by Thalhammer** [comment]
I just tested it and the following compiles just fine:
```c++
class sample {
public:
    jwt::verifier<jwt::default_clock, jwt::picojson_traits> m_verify;
    sample() 
        : m_verify{jwt::verify()}
    {
        m_verify.allow_algorithm(jwt::algorithm::rs256(rsa_pub_key, rsa_priv_key, "", "")).with_issuer("auth0");
    }
};

int main(int argc, const char** argv) {
    sample s;
	auto decoded = jwt::decode(token);
	s.m_verify.verify(decoded);
	for (auto& e : decoded.get_header_claims())
		std::cout << e.first << " = " << e.second.to_json() << std::endl;
	for (auto& e : decoded.get_payload_claims())
		std::cout << e.first << " = " << e.second.to_json() << std::endl;
}
```
Here is the full example, just with .txt cause github does not like .cpp.
[example.cpp.txt](https://github.com/Thalhammer/jwt-cpp/files/5898665/example.cpp.txt)

**Comment by akanksha23new** [comment]
Thanks this compiles fine, however gives a runtime exception:   
 [json.exception.type_error.302] type must be string, but is null, err2=0

Also can i disable picojson and then try to define a default object to verifier ?
jwt::verifier<jwt::default_clock> m_verify;

**Comment by prince-chrismc** [comment]
> [json.exception.type_error.302] type must be string

That does not come from picojson 😖 

Please share your system information along with a small snippet of code such that we can help.

**Comment by akanksha23new** [comment]
Yes, you are right, i was mistake at my end while passing the key. 
Rectified same.
Below are system details:
OS: Linux Centos 7
Compiler :gcc (GCC) 5.4.0

Also verification works now as per code you shared. No issues at my end now.
I have used Nlohmann traits so used :   
Validator::Validator()
: messageValidator_{jwt::verify<jwt::default_clock, nlohmann_traits>({})}

Also i see in example nolhmann_traits struct is not present in lib and need to be defined at users end.
Please correct in case i am missing something.

**Comment by prince-chrismc** [comment]
> Thanks a lot, verification works now as per code you shared. No issues at my end now.

🎉 

You are correct the nlohmann_traits are not public yet, soon 🙏
