### ISSUE TITLE
Availability of v0.5.0 on Windows as VCPKG

### ISSUE THREAD

**Issue by kiddigital** [Thalhammer/jwt-cpp#135]
At the moment, the latest v0.5.0 version is not (yet) available as a Package in Microsofts C++ package library.

The previous version, v.0.4.0 is available, see https://vcpkg.info/port/jwt-cpp

Would be great to get the v0.5.0 available as well.

JWT-CPP is the ONLY package in this library providing JWT support. Also it is the best :)

https://github.com/microsoft/vcpkg/tree/master/ports/jwt-cpp

**Comment by prince-chrismc** [comment]
I am a contributor for Conan so it will feel a little bit of treason but I'll take a look.

**Comment by prince-chrismc** [comment]
Hopefully the PR gets merged quickly!

**Comment by kiddigital** [comment]
Thanks a lot @prince-chrismc , just got the notification that the PR has been merged. The v0.5.0 release is now part of the VCPKG master branch :)

**Comment by prince-chrismc** [comment]
Enjoy!
