### ISSUE TITLE
Null type support in type traits

### ISSUE THREAD

**Issue by JoeStaines** [Thalhammer/jwt-cpp#137]
We have the case where we do sometimes expect null values in the json we receive, and we were filtering it before with get_type(), but with the move to generic type traits i see that it was taken out. Any reason that a generic null type trait isn't supported?

**Comment by prince-chrismc** [comment]
There's no JWT header or payload claim which uses that type, so there was no need for it. It was the same for JSON binary type as well.

That being said, I understand your private claims may be making use of it and in that case you can access the value from the underlying JSON library/object.

- Example: Working with custom private claims

https://github.com/Thalhammer/jwt-cpp/blob/b45bc9994d8087c5ba7aa1f1588302f04ae84c83/example/private-claims.cpp#L145

- Example: Setting a custom private claim

https://github.com/Thalhammer/jwt-cpp/blob/b45bc9994d8087c5ba7aa1f1588302f04ae84c83/example/private-claims.cpp#L11-L13
https://github.com/Thalhammer/jwt-cpp/blob/b45bc9994d8087c5ba7aa1f1588302f04ae84c83/example/private-claims.cpp#L33

**Comment by Thalhammer** [comment]
jwt-cpp is not really designed to serve as an abstraction for a json library. As a result the typetraits only include whats needed to parse and validate a jwt. If you use nonstandard fields you need to interface with the json library you are using (picojson by thefault) and use their functions. To get a raw json value you can use code like this:
```c++
// element is of type 'json_traits::value_type', which is picojson::value by default
auto element = decoded.get_payload_claims()["object"].to_json(); 
 ```
You can then use everything thats available. In case of picojson you could do the following:
```c++
if(element.is<picojson::null>()) { /* It was null */ }
else { /* Its something else */ }
```

I hope this helps and gives some insight into why stuff is the way it is.
