### ISSUE TITLE
What was the default json_traits

### ISSUE THREAD

**Issue by ray42** [Thalhammer/jwt-cpp#138]
**Describe the impediment**
Recently our builds started failing, and it was because the verifier class is now has a new template parameter `json_traits`.
Was the default json_trait before this change,  `jwt::picojson_traits`? I noticed that was mentioned in the README it said "In order to maintain compatibility, picojson is still used to provide a specialized jwt::claim along with all helpers.". I just want the same behaviour as before.

**Desktop (please complete the following information):** (Include/Attach if Applicable)
 - OS:  Windows 10
 - Compiler: msvc
 - Version latest

**Comment by Thalhammer** [comment]
Yes you are correct, its `jwt::picojson_traits`.

**Comment by ray42** [comment]
Thank you for the prompt response! I'll close this issue now :)
