### ISSUE TITLE
Compiling warning

### ISSUE THREAD

**Issue by NickYang1988** [Thalhammer/jwt-cpp#139]
Hi, thanks for this excellent project, it helps me much.

But when I use it to gen a JWT-token, there is a warning,  this private member is unused, could you fix this warning? Thanks.

```
3rdparty/jwt-cpp/include/jwt-cpp/jwt.h:1177:20: warning: private field 'md' is not used [-Wunused-private-field]
                        const EVP_MD* (*md)();
                                        ^
```

**Comment by prince-chrismc** [comment]
It's fixed in master  😄 

#136

**Comment by NickYang1988** [comment]
Thanks.
