### ISSUE TITLE
validating issued_at alway return token expired?

### ISSUE THREAD

**Issue by mdy405** [Thalhammer/jwt-cpp#14]
`
if (jwt.has_issued_at()) {
				auto leeway = claims.count("iat") == 1 ? 
                                std::chrono::system_clock::to_time_t(claims.at("iat").as_date()) : default_leeway;
				auto iat = jwt.get_issued_at();
				if (time < iat - std::chrono::seconds(leeway))
					throw token_verification_exception("token expired");
			}`

leeway = 0 so time  < iat! who else got this ?

**Comment by Thalhammer** [comment]
Sorry for the long delay.

iat is the time where the token was created.
It should not be valid before that time for obvious reasons.
Time is the current time as a time_t, so it is valid if the current time is larger than the time specified in iat.
Are you referring to the fact that a token is not valid in the second it was created (time == iat) ?
I couldn't find any information on how this case should be handled in the spec.

I might have understood your issue wrong, can you please provide more information on your concern ?

**Comment by mdy405** [comment]
thank you for responding generously,

i think you show up the problem...i m testing the verify function where the iat and the current time is separate by a few seconds .... I always got token expired exception

**Comment by Thalhammer** [comment]
Yeah the message might be a bit missleading.
Add a leeway, its common practice to do so anyway as clocks can be off a couple of seconds.

**Comment by mdy405** [comment]
iat = 2019-04-08 14:30:24-04
expiration =  2019-04-08 14:45:24-04
curentTime = 2019-04-08 14:33:24-04
leeway =60 (seconds)

but validation failed at if (time < iat - std::chrono::seconds(leeway))

**Comment by Thalhammer** [comment]
@mdy405 That should indeed be fine. Ill take a look later and test it.

**Comment by Thalhammer** [comment]
@mdy405 I can't reproduce the issue. Can you send me a sample token for debugging purposes?
Does not matter if it is still valid, I can adjust my clock to match.

**Comment by mdy405** [comment]
try this one : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJhdWQiOiJhcHBsaWNhdGlvbl90ZXN0IiwiZGV2aWNlIjoiZGV2aWNlX3Rlc3QiLCJleHAiOjE1NTQ3NDk0OTEsImlhdCI6MTU1NDc1MjE5MSwiaXNzIjoiUFNsaWNlbmNlIiwibGFuZyI6IiIsInNlc3Npb24iOiJlMWM4Zjg4Yi1mMGExLTQ3NjgtYjYwNS01OGU2MGJjNzNiMTMiLCJzdWIiOiIyIn0.IC0Ycv_essCYeSsbxQuuH42RLGr8bjj5b-g-OQpzoIw" 
algo: H256
secret: "secret"

**Comment by Thalhammer** [comment]
Do you use jwt-cpp for creating that token?
Because for some reason the iat time is in the future (well beyong exp and even the current time).

**Comment by mdy405** [comment]
yes i use  jwt-cpp like below:
`
       std::tm tm = {};
	std::istringstream iss(now); //now is a string formatted datetime
	iss >> std::get_time(&tm, "%Y-%m-%dT%H:%M:%SZ");

	auto tp = std::chrono::system_clock::from_time_t(std::mktime(&tm));
	auto expiresAt = tp+std::chrono::minutes(configuration_>getTokenDuration());
	auto token = jwt::create()
			.set_issuer("licence")
				.set_subject(result.userId)
				.set_audience(result.applicationName)
				.set_expires_at(jwt::date(expiresAt))
				.set_issued_at(jwt::date(tp))
				.set_type("JWS")
				.set_payload_claim("session",result.id)
				.set_payload_claim("device",result.deviceId)
				.set_payload_claim("lang", result.language)
			        .sign(jwt::algorithm::hs256{"secret"});
`

**Comment by Thalhammer** [comment]
@mdy405 I cleaned your code a bit and added a static time.

```
std::string now = "2019-04-08T21:35:21Z";
	std::tm tm = {};
	std::istringstream iss(now); 
	iss >> std::get_time(&tm, "%Y-%m-%dT%H:%M:%SZ");
	auto tp = std::chrono::system_clock::from_time_t(std::mktime(&tm));
	auto expiresAt = tp+std::chrono::minutes(60);
	auto token = jwt::create()
			.set_issuer("licence")
			.set_expires_at(jwt::date(expiresAt))
			.set_issued_at(jwt::date(tp))
			.set_type("JWS")
			.sign(jwt::algorithm::hs256{"secret"});
	std::cout << token << std::endl;
```
It is generating a valid token and the issue is not present there, are you sure the code you posted is the code you use to generate the token?
Are you using the current version (master branch 2b3ddae I did not fix anything related to time as far as I know but just to make sure)?

**Comment by mdy405** [comment]
it's definitely weird i used the same code but unable to validate the token!

**Comment by mdy405** [comment]
I think i found the issue for some unknown reason(at the moment) i got a bad timestamp while converting my string to timepoint. i got:
iat =1554757219000000000 && exp = 1554758119000000000

**Comment by Thalhammer** [comment]
@mdy405 but those look right ;)

**Comment by Thalhammer** [comment]
Is this solved @mdy405 ?

**Comment by Thalhammer** [comment]
Closed due to inactivity.
