### ISSUE TITLE
"'argument': conversion from 'size_t' to 'long', possible loss of data" Windows build x64

### ISSUE THREAD

**Issue by TaeZStkyoht** [Thalhammer/jwt-cpp#140]
My OS is Windows and I'm using the latest version (0.5.0) that vcpkg provides. There was no warning on the previous version (0.4.0) but this version has. If I build x86 then there is no problem; however, If I build x64 (both Debug and Release) then it gives warnings below and it's really annoying:

```
"blabla\vcpkg\installed\x64-windows\include\jwt-cpp\jwt.h(441,1): warning C4267: 'argument': conversion from 'size_t' to 'long', possible loss of data"
```

The problem is in the 'convert_base64_der_to_pem' function's line:

https://github.com/Thalhammer/jwt-cpp/blob/4620bf43befea5ef69816fb8610723232a609030/include/jwt-cpp/jwt.h#L441

**Comment by prince-chrismc** [comment]
I saw this too... I push a fix soon
