### ISSUE TITLE
[bug] Defining NOMINMAX still leads to compilation errors

### ISSUE THREAD

**Issue by debasis09** [Thalhammer/jwt-cpp#144]
**Describe the bug**
I am creating a MFC shared dll project .
I have included `"jwt-cpp\jwt.h"` in my .cpp file.
I have given the proper include path and openssl lib in project settings.
while I am trying to compile in 64 bit
 I am receiving errors from include\picojson\picojson.h and 
\microsoft visual studio 14.0\vc\include\xutility(2982).

If I am creating a Console Application in C++ and do the same thing.
It is getting compiled successfully

**How To Reproduce** (Include if Applicable)
Please provide a small snippet to reproduce the issue

**Expected behavior**
should be compiled successfully.

**Screenshots**
As suggested in readme file I have done like below in my class .cpp file

```cpp
#include "jwt-cpp\jwt.h"
#include <iostream>

#define NOMINMAX
#include <Windows.h>
```

**Desktop (please complete the following information):**
 - OS: Windows10
 - Compiler Microsoft C++ Compiler,target x64
 - Version VS2015

**Additional context**

**Logs** (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
jwt-cpp-master\include\picojson\picojson.h(910): error C2059: syntax error: '::'
jwt-cpp-master\include\picojson\picojson.h(911): error C2143: syntax error: missing ';' before '{'
jwt-cpp-master\include\picojson\picojson.h(917): error C2065: 'f': undeclared identifier
jwt-cpp-master\include\picojson\picojson.h(917): error C2065: 'num_str': undeclared identifier
jwt-cpp-master\include\picojson\picojson.h(917): error C2228: left of '.c_str' must have class/struct/union
1>  c:\gcss release\roys_poc\gcssfeb2c auth\jwt-cpp-master\jwt-cpp-master\include\picojson\picojson.h(917): note: type is 'unknown-type'
jwt-cpp-master\include\picojson\picojson.h(917): error C2065: 'endp': undeclared identifier
jwt-cpp-master\include\picojson\picojson.h(918): error C2065: 'endp': undeclared identifier
jwt-cpp-master\include\picojson\picojson.h(918): error C2065: 'num_str': undeclared identifier
jwt-cpp-master\include\picojson\picojson.h(918): error C2228: left of '.c_str' must have class/struct/union
1>  c:\gcss release\roys_poc\gcssfeb2c auth\jwt-cpp-master\jwt-cpp-master\include\picojson\picojson.h(918): note: type is 'unknown-type'
jwt-cpp-master\include\picojson\picojson.h(918): error C2228: left of '.size' must have class/struct/union
1>  c:\gcss release\roys_poc\gcssfeb2c auth\jwt-cpp-master\jwt-cpp-master\include\picojson\picojson.h(918): note: type is 'unknown-type'
jwt-cpp-master\include\picojson\picojson.h(919): error C2065: 'f': undeclared identifier
jwt-cpp-master\include\picojson\picojson.h(924): error C2043: illegal break
jwt-cpp-master\include\picojson\picojson.h(926): error C3927: '->': trailing return type is not allowed after a non-function declarator
jwt-cpp-master\include\picojson\picojson.h(926): error C3484: syntax error: expected '->' before the return type
jwt-cpp-master\include\picojson\picojson.h(926): error C3613: missing return type after '->' ('int' assumed)
jwt-cpp-master\include\picojson\picojson.h(926): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
jwt-cpp-master\include\picojson\picojson.h(926): error C2146: syntax error: missing ';' before identifier 'ungetc'
jwt-cpp-master\include\picojson\picojson.h(927): error C2059: syntax error: 'return'
jwt-cpp-master\include\picojson\picojson.h(928): error C2059: syntax error: '}'
jwt-cpp-master\include\picojson\picojson.h(928): error C2143: syntax error: missing ';' before '}'
1>c:\program files (x86)\microsoft visual studio 14.0\vc\include\xutility(2982): error C2143: syntax error: missing ';' before '{'
1>c:\program files (x86)\microsoft visual studio 14.0\vc\include\xutility(2982): error C2447: '{': missing function header (old-style formal list?)
```

</details>

**Comment by Thalhammer** [comment]
Seems like min/max is still defined as a macro despite NOMINMAX being defined. Are you sure Windows.h is never included before the macro is defined?

**Comment by debasis09** [comment]
I just searched my project. Windows.h is not included before the macro. I have also moved this below code on top of my header file but received same error.For my code Windows.h is not required.To use "jwt-cpp\jwt.h" I have included it. Even if I compiled keeping only NOMINMAX and without including  Windows.h still the errors are same.

#define NOMINMAX
#include <Windows.h>

**Comment by prince-chrismc** [comment]
The define needs to be placed before you include any headers, something like this

```cpp
#define NOMINMAX
#include "jwt-cpp\jwt.h"
```

Maybe give that a try and let us know!

**Comment by debasis09** [comment]
I have tried with putting the below lines very top of the .cpp file 
#define NOMINMAX
#include "jwt-cpp\jwt.h"

now received different errors

1>jwttokendecoder.cpp(2): warning C4603: 'NOMINMAX': macro is not defined or definition is different after precompiled header use
1>  jwttokendecoder.cpp(2): note: Add macro to precompiled header instead of defining here
1>  jwttokendecoder.cpp(5): note: use of precompiled header
1>jwttokendecoder.cpp(147): error C2653: 'jwt': is not a class or namespace name
1>jwttokendecoder.cpp(147): error C3861: 'decode': identifier not found
1>jwttokendecoder.cpp(148): error C2228: left of '.get_payload_claims' must have class/struct/union
1>  jwttokendecoder.cpp(148): note: type is 'unknown-type'
1>jwttokendecoder.cpp(149): error C2065: 'e': undeclared identifier
1>jwttokendecoder.cpp(149): error C2228: left of '.first' must have class/struct/union
1>  jwttokendecoder.cpp(149): note: type is 'unknown-type'
1>jwttokendecoder.cpp(149): error C2228: left of '.second' must have class/struct/union
1>  jwttokendecoder.cpp(149): note: type is 'unknown-type'
1>jwttokendecoder.cpp(149): error C2228: left of '.to_json' must have class/struct/union

**Comment by Thalhammer** [comment]
Ahh I think I see whats going on. You seem to use precompiled headers. Thats a single header that should contain all headers you frequently use (like windows.h). It allows the compiler to speed up compilation by only parsing those headers once. I believe it gets automatically included in every file if enabled, which is why you include windows.h even if you dont in your source file. Try placing the NOMINMAX macro at the start of your pch.h or disable precompiled headers if you dont need them.

**Comment by debasis09** [comment]
I disabled the use of precompiled headers as I don't need them and it worked like a charm!!.
Thank you so much for your support.

**Comment by prince-chrismc** [comment]
Glad we could help!
