### ISSUE TITLE
Exp verification fails for dates in the far future

### ISSUE THREAD

**Issue by etyink** [Thalhammer/jwt-cpp#15]
Tokens with expiration dates in the far future (roughly beyond year 2250) are not calculated properly on Debian. I believe this is actually either a problem (or limitation) of using std::chrono::system_clock when getting exp as a date. 

I have a JWT with an exp date as: `15393024000` that we use for testing purposes and it fails validation. The resulting local time of that exp in the verifier is `03/25/1873 19:29:25`. Below is the code I was using to print that from within the verifier:
```
auto exp_tt = std::chrono::system_clock::to_time_t(exp);
std::tm * ptm = std::localtime(&exp_tt);
char buffer[32] = {0};
std::strftime(buffer, 32, "%m/%d/%Y %H:%M:%S", ptm);
printf("Exp: %s\n", buffer);
```

I did not try every permutation of dates but the latest I tried that seemed to work was this: `8860621278` which corresponds to `10/13/2250 11:41:18`

Any guidance on this would be much appreciated, I was unable to find any documentation on limitations of the system_clock and this issue did not seem to arise on Windows or Mac OS.

**Comment by Thalhammer** [comment]
Hi and thank you for checking such extreme cases.
I did some checking and found the exact date it will fail:
04/11/2262 @ 11:47pm (UTC)

What your hitting is the maximum value of a 64bit long (9223372036).
jwt-cpp uses a std::chrono::system_clock::time_point to store time and date information.
At least on my system (and I guess most) this is a typedef to `std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >`, i.e. the time_t value in nanoseconds.

Is this a real problem for your application or just a theoretical one?

**Comment by etyink** [comment]
Thanks for the quick response and guidance. Its really just a theoretical one, we just have a JWT for convenience with such a long expiration time. It's kind of a shame these limits aren't more documented, but I suppose since its implementation specific it would be kind of hard. 

Thanks again!
