### ISSUE TITLE
[bug] Vcpkg Error for version 0.5.1

### ISSUE THREAD

**Issue by TaeZStkyoht** [Thalhammer/jwt-cpp#161]
**Describe the bug**
I'm getting an error while installing the latest (0.5.1) version.

**How To Reproduce** (Include if Applicable)
vcpkg install jwt-cpp

**Expected behavior**
Successfully installing via vcpkg

**Screenshots**
![image](https://user-images.githubusercontent.com/3801692/131625640-e016f27b-fd6b-4177-949a-71b60b3cd464.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Logs** (Include/Attach if Applicable)
<details><summary>Click to expand Vcpkg log</summary>
C:\Users\oguzhan>vcpkg install jwt-cpp
Computing installation plan...
The following packages will be built and installed:
    jwt-cpp[core]:x86-windows -> 0.5.1
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\oguzhan\AppData\Local\vcpkg\archives\93\93006bc4d56ec131778cf1ee3c4bb518bba83bb487fb9d25a80e4e02327f2cf8.zip
Starting package 1/1: jwt-cpp:x86-windows
Building package jwt-cpp[core]:x86-windows...
-- Downloading https://github.com/Thalhammer/jwt-cpp/archive/60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz -> Thalhammer-jwt-cpp-60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://github.com/Thalhammer/jwt-cpp/archive/60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://github.com/Thalhammer/jwt-cpp/archive/60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz ]
       File path : [ C:\Projects\vcpkg\downloads\Thalhammer-jwt-cpp-60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz.14380.part ]
   Expected hash : [ d2c6e2174cd86c27b8866f6ea50a379a321788e91f97a0548e694d11469c05d93b0713e0c38b37a8f14a0aded4fc4635599dcfb50142e4496fb3c8b9f7e5f8cd ]
     Actual hash : [ ae905e217824d21ec9f098f562d993fbae71b2223e65f3bbcc29d352af61f2aa09b5c6b12c7d94742901a1374f9683335d3b4934c25b11500b710398331f6cb4 ]

[DEBUG] C:\a\1\s\src\vcpkg\base\downloads.cpp(626)
[DEBUG] Exiting after 718058 us (712411 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:83 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:274 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:173 (vcpkg_download_distfile)
  ports/jwt-cpp/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:140 (include)

Error: Building package jwt-cpp:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: jwt-cpp:x86-windows
  Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

Additionally, attach any relevant sections from the log files above.
</details>

**Comment by pyrotechnics-io** [comment]
https://github.com/microsoft/vcpkg/issues/19837

**Comment by TaeZStkyoht** [comment]
> [microsoft/vcpkg#19837](https://github.com/microsoft/vcpkg/issues/19837)

Thanks
