### ISSUE TITLE
failed to load public key: PEM_read_bio_PUBKEY failed

### ISSUE THREAD

**Issue by dantti** [Thalhammer/jwt-cpp#17]
Hi,

I tried to change the sources to use PEM_read_bio_RSA_PUBKEY or PEM_read_bio_RSAPublicKey, to no effect, I'm trying to verify the signature of this [token](https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjVmYjMyOWRmNjdiYjY4NDVkNDk1NDNiMGM0OWIzNWM4ODg1NzllYmEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBwdGluYS01ZDEyNyIsImF1ZCI6ImFwcHRpbmEtNWQxMjciLCJhdXRoX3RpbWUiOjE1NTU1MTE4MTYsInVzZXJfaWQiOiJTMXdsM3FPYUJ0WU16SXJ2dTZaNEI0TlFyMm4xIiwic3ViIjoiUzF3bDNxT2FCdFlNeklydnU2WjRCNE5RcjJuMSIsImlhdCI6MTU1NTUxMTgxNiwiZXhwIjoxNTU1NTE1NDE2LCJwaG9uZV9udW1iZXIiOiIrNTUxMTk4MjY4MzMxOCIsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsicGhvbmUiOlsiKzU1MTE5ODI2ODMzMTgiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwaG9uZSJ9fQ.jSucyTSHB9R7glWKnmaMMrygC1gzEk0L0QsFkjfRsUc8M8cAMJefJU7MOn7StGeQlVeWAU1L9gps6lploAniImn29PGnK5TjI9DFejifvP1rmLwoW1wLY3KUUvlhrFPme99RsuTwRkCVT_uIBG8GCKn7DP38rAOHkIkEo1Z6nuBuh5PcO6pumakm-s94GrR20BSeoqnEnnvIPnNkC0Xex94xcy8BpKQh98naEKxuIEgoxneERVg7gA7yly_E4iFdpuMr_YCyzFOczQA7_iy2Z-OwvVLm8U9HqAfdtNbITqr6m544E6QpVOqJXrMCBmGP3pRaYS6UBaUIDS5wm74k8A&publicKey=-----BEGIN%20CERTIFICATE-----%0AMIIDHDCCAgSgAwIBAgIIGlbUz5cvweUwDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE%0AAxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMTkw%0ANDEwMjEyMDUxWhcNMTkwNDI3MDkzNTUxWjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl%0Abi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD%0AggEPADCCAQoCggEBALRPFSsUi%2FbGcMVkD%2BXjJ6z%2F71u%2B7Wn1C1bRnM9sU3q7%2BEre%0ADV6an%2Bz%2BYsjblskBX73h1GyYvmtkyuL7Uq0N%2By%2BRTOmd2fwDw48gM5FEq6DNpVVW%0AZRIzzoMSLZCB%2Btg1eQZdGKtmctdd5Jjhwihf9Aa759fcj60GDG39G6A%2Fw4Jok%2BJ6%0A7sRabxxontJ4Kpo6zmwUKbWF8naJeCRTO0VAYLkJqEWO4VJTIHJeu2WpxM0qzvY9%0AIY5Yd7Njegu64FoHU55dSfee2KwDa0%2FbajrknJfxWBN4hk%2FrqgGjxQmzAYMCB7%2Fp%0A%2F9Snfg4NmfX5cJJ01SNzY6Q%2FmJRjB3iX2PBz%2BGsCAwEAAaM4MDYwDAYDVR0TAQH%2F%0ABAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH%2FBAwwCgYIKwYBBQUHAwIwDQYJ%0AKoZIhvcNAQEFBQADggEBAKCSq0D%2BNIAsGULZrhXouurxInxDyq03xLNcxvKDQchc%0AXfGA1r3eltmlyKQb5TmAsuKwS%2FLAQ5z8SlRTOmDGVEtDwnw3S83C4ufXbP0eMB6H%0AeKf2XCA00T3odUfXmQZme8hG6z7GKVOdn%2F0oY%2BvaX38brlCpRXDTm1WldyddUpMz%0Aftcs6dibdnbQtbX6o9E%2BKuvGHoNW5xcSjX8lwXTpopfvufPOLPcnFXi4UoYZ8NZ2%0A2mRG78LkOA%2BSkOMutbt6w7TBDvADmFzuzvAULy4gsfcamOYcQ7uiHnnD%2BPoNiNbw%0AflE%2Fm%2F0zymX8I%2FXu3%2BKKLhUnUROGC6zO3OnLHXCnEns%3D%0A-----END%20CERTIFICATE-----).
Tried to change CERTIFICATE to PUBLIC KEY, but no luck, any tips?

Thanks

**Comment by Thalhammer** [comment]
A certificate is a superset of a public key. Amongst the public key, it also contains information like the issuer, expected uses and so on. You can use openssl to extract the public key like so:

`openssl x509 -pubkey -noout -in google_cert.pem  > pubkey.pem`

The extracted public key works fine, I just tried it.

**Comment by dantti** [comment]
It indeed works, thanks, do you happen to have a code snippet to do the above without resorting to command line?

**Comment by Thalhammer** [comment]
I have not tried it, but this:
http://fm4dd.com/openssl/certpubkey.htm
and this:
https://www.openssl.org/docs/manmaster/man3/BIO_s_mem.html
Looks like a good solution.

**Comment by dantti** [comment]
Thanks, perhaps consider having this build-in? :)
