### ISSUE TITLE
[bug] Boost traits test does not compile

### ISSUE THREAD

**Issue by Etienne-P54** [Thalhammer/jwt-cpp#173]
Hello,

I am very interested in your library. I just tried to compile the Boost JSON traits example on Mac OS (Apple clang version 12.0.5 (clang-1205.0.22.11)) and I get the following error:

```
/usr/local/include/jwt-cpp/jwt.h:1871:4: error: static_assert failed due to requirement 'is_valid_json_object<boost::json::value, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, boost::json::object>::value' "object_type must be a string_type to value_type container"
                        static_assert(is_valid_json_object<value_type, string_type, object_type>::value,
                        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/jwt-cpp/jwt.h:1903:13: note: in instantiation of template class 'jwt::details::is_valid_json_types<boost::json::value, std::__1::basic_string<char>, boost::json::object, boost::json::array>' requested here
                        details::is_valid_json_types<typename json_traits::value_type, typename json_traits::string_type,
                                 ^
BoostJsonTest.cpp:81:22: note: in instantiation of template class 'jwt::basic_claim<boostjson_traits>' requested here
        const auto string = boostjson_claim(boostjson_traits::string_type("string"));
```

Do you have any idea ?
Thank you

**Comment by prince-chrismc** [comment]
The Boost.JSON support is very new!

❓ Are you using the "standalone mode" with C++17?

 There's a few requirements you need to follow, for it to work, they are outlined in https://github.com/Thalhammer/jwt-cpp/pull/165#issue-989560548 .If you are using CMake you can do the following

https://github.com/Thalhammer/jwt-cpp/blob/b47d095741510204eda7e7d41a9b9fc8e093fe54/tests/boost/CMakeLists.txt#L16-L17

I was not able to get a full installation of Boost with C++11 to work as Boost.JSON implementation is far different from the STL API. You can see my comments in #164

**Comment by Etienne-P54** [comment]
Yes, I saw that you landed this Boost.JSON support only a few days ago.
In my setup, the Boost.JSON library is compiled in C++17 using the standalone mode.
In fact I'm just trying to compile jwt-cpp/tests/boost using your CMakeLists.txt

**Comment by prince-chrismc** [comment]
Hmm, very odd... Can you please share the logs for configuring CMake and building?
https://github.com/Thalhammer/jwt-cpp/runs/3613875552?check_suite_focus=true#step:6:26 our CI is passing with GCC-9.3 there might just be an issue with Clang 🤔

**Comment by Etienne-P54** [comment]
I retried using the header only standalone version of Boost.JSON and not the shared library and it works...
Thanks for your help anyway and keep up the good work

**Comment by prince-chrismc** [comment]
Hmm I did not try the compiled library... I'll see what the issue was. I updated the PR description to add that as a requirement in the time being.

**Comment by prince-chrismc** [comment]
Since you are not using the default traits, I have a small question for you.

On a scale of 0 to 10 (low to high respectively) would you be interested in the traits being provided?

I am thinking of moving he traits to a subfolders so downstream can just use the ones them and not have to copy paste the code.
Would the be a good addition?

**Comment by Etienne-P54** [comment]
I would rate it 10 !!!
the provided traits for the different json libraries can be used as is. so including them would simplify the use of your library.

**Comment by Etienne-P54** [comment]
I finally undertsood my mistake.
The support for Boost.JSON works in your master branch but not yet any in the released / pre-release versions and my application build script fetches only released versions (v.0.5.1) hence the bug.
Do you plan to tag a version including Boost.JSON support soon ?
Thanx

**Comment by Thalhammer** [comment]
There is a 0.6.0 prerelease and we will release the current Master again once hunter support is figured out.
