### ISSUE TITLE
error 'EC_KEY_free': Since OpenSSL 3.0	

### ISSUE THREAD

**Issue by Ruuddenbekker** [Thalhammer/jwt-cpp#181]
L.S.,

when trying to build an application using jwt-cpp, I get the following errors:
1>D:\VisualStudioProjects\cpp_jwt\include\jwt\impl\algorithm.ipp(113,24): error C4996: 'EVP_PKEY_get1_EC_KEY': Since OpenSSL 3.0
1>D:\VisualStudioProjects\cpp_jwt\include\jwt\impl\algorithm.ipp(119,9): error C4996: 'EC_KEY_get0_group': Since OpenSSL 3.0
1>D:\VisualStudioProjects\cpp_jwt\include\jwt\impl\algorithm.ipp(264,22): error C4996: 'EVP_PKEY_get1_EC_KEY': Since OpenSSL 3.0
1>D:\VisualStudioProjects\cpp_jwt\include\jwt\impl\algorithm.ipp(271,41): error C4996: 'EC_KEY_get0_group': Since OpenSSL 3.0

Any idea what is causing this?

Best regards,

Ruud

**Comment by prince-chrismc** [comment]
Feel free to switch 💟
