### ISSUE TITLE
RSA sign only with private key??

### ISSUE THREAD

**Issue by p4w4n** [Thalhammer/jwt-cpp#182]
I am using your library on a legacy system which still run gcc 4.6. with that I am forced to use the older version of your library that you released in 2019. Although the question is more general.

I see that the jwt create with RSA still needs the public and private keys. I am trying to create a jwt for a GCP service using a service account. The service account only provides a private key and there is no public key present. 

Is it possible to create a JWT and sign it with the private key only and skip the public key? If yes, can you please give me some suggestions about it.

Thanks!!!

**Comment by prince-chrismc** [comment]
To the best of my knowledge, if you pass both only the private is used. See

https://github.com/Thalhammer/jwt-cpp/blob/ab1a60ec8af13d5f508fc32881e103d84f2d876b/include/jwt-cpp/jwt.h#L784

So you should be able to pass only the private when you are signing. These APIs haven't changed so it should work on older versions.

**Comment by Thalhammer** [comment]
Chris is perfectly right. Simply supply an empty string for the public key.
