### ISSUE TITLE
 jwt::verifier<jwt::default_clock>::algo_base::~algo_base() unresolved reference

### ISSUE THREAD

**Issue by p4w4n** [Thalhammer/jwt-cpp#19]
Hey,

Thanks for the great library. However when I am trying to compile the code I am getting an unresolved reference for jwt::verifier<jwt::default_clock>::algo_base::~algo_base().

Error: unresolved references found. 
jwt::verifier<jwt::default_clock>::algo_base::~algo_base()

Can you please help.

Thanks a lot!!!

**Comment by Thalhammer** [comment]
What compiler/OS are you using?
Any special compiler flags?

**Comment by p4w4n** [comment]
cpp --version
cpp (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

**Comment by Thalhammer** [comment]
Do you get the error when trying to compile the test cases?
gcc 4.8.5 is pretty old, make sure you compile with -std=c++11

**Comment by p4w4n** [comment]
Yes, I get this while compiling the test cases and/or with my own code
where I am calling jwt decode. I am actually working on a legacy system and
looks like it doesn't support c++11(it does support c++0x). When I
commented out the virtual ~algo_base(), the unresolved reference went away.

Do you think commenting out the virtual destructor will have and adverse
effect?

**Comment by Thalhammer** [comment]
> Do you think commenting out the virtual destructor will have and adverse effect?

Yes absolutely. The virtual destructor is needed to allow the algorithm to be destroyed. If you remove it you WILL leak memory everytime you create/destory a verifier.

You can try replacing the line

`virtual ~algo_base() = default;`

with

`virtual ~algo_base() {}`

This might fix it, if it compiles fine otherwise.

**Comment by p4w4n** [comment]
> > Do you think commenting out the virtual destructor will have and adverse effect?
> 
> Yes absolutely. The virtual destructor is needed to allow the algorithm to be destroyed. If you remove it you WILL leak memory everytime you create/destory a verifier.
> 
> You can try replacing the line
> 
> `virtual ~algo_base() = default;`
> 
> with
> 
> `virtual ~algo_base() {}`
> 
> This might fix it, if it compiles fine otherwise.



Thanks a lot!!! Converting it to a function resolved the issue. :)
