### ISSUE TITLE
[question] Example with using builder explicitly

### ISSUE THREAD

**Issue by p4w4n** [Thalhammer/jwt-cpp#190]
Hey,

I am looking for an example where we have used the builder explicitly to create the JWT token.  I tried with

```cpp
auto builder = jwt::create();
```

but I am getting templating issues. Do you have any example?

Thanks

**Comment by Thalhammer** [comment]
https://github.com/Thalhammer/jwt-cpp/blob/master/example/rsa-create.cpp

Contains an example on how to use the builder. Or do you mean storing the builder and building in multiple steps ?

**Comment by p4w4n** [comment]
Yes, I want to create the token in multiple steps using a builder.

**Comment by prince-chrismc** [comment]
I believe it should be `jwt::builder<jwt::picojson_traits> local_build;`
We had similar question about the verifier https://github.com/Thalhammer/jwt-cpp/issues/130.

If we did not understand your question, please provide a small code sample + the build logs so we can help resolve the compilation issues.

***
For my reference this line does the magic

https://github.com/Thalhammer/jwt-cpp/blob/55aaf31ad852e0b4666b2daf6b8b9e2e68b6c04a/include/jwt-cpp/jwt.h#L3598

**Comment by prince-chrismc** [comment]
Closing this question as "resolved" if you still have problem feel free to reopen the issue.

**Comment by p4w4n** [comment]
Hey - can you please provide an example again how to use the builder explicitly as you did in the example you provided above. With the recent changes, I am getting an error about adding the default_clock and can't get it to work.

**Comment by prince-chrismc** [comment]
https://github.com/Thalhammer/jwt-cpp/blob/364a5572f4b46bb9f4304cb1c92acec8ddb2c620/include/jwt-cpp/traits/kazuho-picojson/defaults.h#L27

There a defaults provide as reference. Hopefully that helps
