### ISSUE TITLE
[question] Can I add claims without id?

### ISSUE THREAD

**Issue by MountainNine** [Thalhammer/jwt-cpp#214]
For example, I want to add payload claims with this JSON format.
`{'test':'hello', 'test2':123}`
I looked jwt.h, and I found 'set_payload_claim' function.
But this function needs 'id' parameter, and I don't want to contain id.
Can I add this payload_claim without adding id?
Thank you.

**Comment by prince-chrismc** [comment]
Hmm 🤔 I am not sure I understood your question so let me know if I missed the mark. 


So JWT are JSON object those are key value pairs. If youd like to add a claim it needs to have a key (the API `id` might be unclear, let us know).

So if you use

https://github.com/Thalhammer/jwt-cpp/blob/9d1a010fea3ed3293112edec9745dc435a85a849/include/jwt-cpp/jwt.h#L2702

Like so

https://github.com/Thalhammer/jwt-cpp/blob/9d1a010fea3ed3293112edec9745dc435a85a849/example/private-claims.cpp#L30

You are able to add any JSON value for the `id` you want to access it with.

And for completeness, here's how youd access the value

https://github.com/Thalhammer/jwt-cpp/blob/9d1a010fea3ed3293112edec9745dc435a85a849/example/traits/kazuho-picojson.cpp#L36

By passing the `id`

**Comment by MountainNine** [comment]
What I want to do is to set payload claim without id.

According to the link,

https://github.com/Thalhammer/jwt-cpp/blob/9d1a010fea3ed3293112edec9745dc435a85a849/example/private-claims.cpp#L30

payload_claims variable is set to this.

`{'object':{'test':'hello', 'test2':123}}`

But I want to set payload_claims like this.

`{'test':'hello', 'test2':123}`

More specifically, I looked jwt.h, and found this code.

https://github.com/Thalhammer/jwt-cpp/blob/9d1a010fea3ed3293112edec9745dc435a85a849/include/jwt-cpp/jwt.h#L2702-L2705

What I want to do is to set payload_claims itself, not payload_claims[id].

I apologize about Insufficient explanation.

**Comment by MountainNine** [comment]
Never Mind, I solved it by adding the function in jwt.h

`
		builder& set_payload(typename json_traits::object_type jsonStr) {
			payload_claims = std::move(jsonStr);
		    return *this;
        }
`

Thanks for help, prince.

**Comment by prince-chrismc** [comment]
Ohh!

You could have called the method twice.

```cpp
builder.set_payload_claim("test", /* json string hello */);
builder.set_payload_claim("test2", /* other */);
```

Thanks for sharing your solution!

PS you might be missing some other claims that are recommended like issuer. Not sure your application or situation but wanted to throw that in.

**Comment by Thalhammer** [comment]
@MountainNine If I understood correctly what you wanted to do is replace the payload claims entirely. You are right that this is not supported by default and the reason for this is simple: JWT **requires** certain claims to be present and set to correct values. Otherwise its not a valid jwt and jwt-cpp (or any other jwt library) will correctly verify it. If you have a third party application that requires exactly this, then your way it probably fine, however if you control the layout of the jwt I highly recommend sticking with the defaults.
