### ISSUE TITLE
[question] Passing json object as entire payload

### ISSUE THREAD

**Issue by ktasyaran** [Thalhammer/jwt-cpp#216]
I looked at examples regarding traits for nlohmann-json. Is there any possibility/workaround to pass a json object as entire payload instead of calling set_payload_claim() for each key I want to specify?

**Comment by prince-chrismc** [comment]
Currently no, you can see the conversation in #214 but they're recommended fields so the API is designed to follow those practices :)

Dont hesitate if you need more details

**Comment by ktasyaran** [comment]
Thanks. I looked at that convo and got the reason behind that now.
