### ISSUE TITLE
RSA Exception

### ISSUE THREAD

**Issue by rakesh850gs** [Thalhammer/jwt-cpp#233]
### What happened?

While trying the example in GitHub 

The below mentioned error is appearing when trying to sign with RS256 , however same code works with HS 256 

Exception thrown at 0x00007FFB356C4FD9 in PluginUnitApp.exe: Microsoft C++ exception: jwt::error::rsa_exception at memory location 0x000000D77DEFE5A8.
Unhandled exception at 0x00007FFB356C4FD9 in PluginUnitApp.exe: Microsoft C++ exception: jwt::error::rsa_exception at memory location 0x000000D77DEFE5A8.

### How To Reproduce?

execute example code in vs2017 with rs256

### Version

0.6.0

### What OS are you seeing the problem on?

Windows

### What compiler are you seeing the problem on?

MSVC

### Relevant log output

```shell
Exception thrown at 0x00007FFB356C4FD9 in PluginUnitApp.exe: Microsoft C++ exception: jwt::error::rsa_exception at memory location 0x000000D77DEFE5A8.
Unhandled exception at 0x00007FFB356C4FD9 in PluginUnitApp.exe: Microsoft C++ exception: jwt::error::rsa_exception at memory location 0x000000D77DEFE5A8.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prince-chrismc** [comment]
Can you share the error message of the exception?

Also how you are making the RSA key and signing the token?

**Comment by rakesh850gs** [comment]
Like below 
auto token = jwt::create()
			.set_issuer("1234567890")
			.set_type("JWS")
			.set_subject("67890063dfgh")
			.set_expires_at(expireTime)
			.set_issued_at(std::chrono::system_clock::now())
			.set_audience("url")
			.set_payload_claim("sample", jwt::claim(std::string("test")))
			.sign(jwt::algorithm::rs256("","secret","",""));

**Comment by prince-chrismc** [comment]
You need to pass a valid RSA private key for the signing algorithm,

Check out this example https://github.com/Thalhammer/jwt-cpp/blob/5d25462e030fa20a7d7e35f5ba70c6ebb61cb1b6/example/rsa-create.cpp#L5

**Comment by rakesh850gs** [comment]
It worked , thanks , since and invalid key worked for HS256 , I thought it would work here too , thanks .
