### ISSUE TITLE
Cannot set jwk to header when generate the JWS

### ISSUE THREAD

**Issue by lzha101** [Thalhammer/jwt-cpp#247]
### What's your question?

Is it possible to add other header parameter names support? 

### Additional Context

From https://www.rfc-editor.org/rfc/rfc7515#section-4.1, it shows JWS supports other Header Parameter names besides `alg`, `kid`, `typ`.   Is it possible to add other header parameter names, such as `jku`, `jkw`, etc?

**Comment by prince-chrismc** [comment]
https://github.com/Thalhammer/jwt-cpp/blob/0628011aebb109a0ec3cdb2499106b5fc718fe5a/include/jwt-cpp/jwt.h#L2756

Should do the trick for you!

**Comment by lzha101** [comment]
Oh, yes. Thanks for the info. I missed this interface. It works for me. Thanks again.
