### ISSUE TITLE
Decode JWT Token (Boost)

### ISSUE THREAD

**Issue by hanusek** [Thalhammer/jwt-cpp#248]
### What's your question?

How to decode JWT token (HS256) with Boost traits?

### Additional Context

Hello. 
I have a token generated by https://jwt.io but I have a problem - Exception: Invalid input: not within alphabet.
How to fix it?
**Encoded:**
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```
**Header:**
```
{
  "alg": "HS256",
  "typ": "JWT"
}
```
**Payload:**
```
{
  "sub": "1234567890",
  "name": "John Doe",
  "iat": 1516239022
}
```
**VERIFY SIGNATURE:**
```
HMACSHA256(
  base64UrlEncode(header) + "." +
  base64UrlEncode(payload), 
your-256-bit-secret
)
```
**Code:**
```
#include <boost/json/src.hpp>
#include <jwt-cpp/traits/boost-json/traits.h>

using traits = jwt::traits::boost_json;
using claim = jwt::basic_claim<traits>;

void jwt_token(const std::string& token)
{
    const auto decoded = jwt::decode<traits>(token);
    std::cout << "decoded token: " << decoded.get_algorithm() << std::endl;
}
```
**Error log:**
```
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
Exception: Invalid input: not within alphabet
```

**Comment by prince-chrismc** [comment]
Hmm I am not able to repoduce 🤔 

https://github.com/prince-chrismc/jwt-cpp/actions/runs/3116500580/jobs/5054387893#step:11:1536

Want to try my code?

**Comment by Thalhammer** [comment]
Glad to hear you solved your issue. jwt-cpp expects a clean token as a parameter, not sure if we should check for preceding/trailing whitespace and remove it. What do you think @prince-chrismc ?

**Comment by hanusek** [comment]
@Thalhammer This problem was very difficult to detect. Because prints were the same. But strings weren't been the same. My string has a lot of white characters inside (Not only on end and begin).

**Comment by prince-chrismc** [comment]
> What do you think @prince-chrismc ?

I think the head of the problem is the error message. When it said it should say `"the character at Index 14 ' ' is not apart of the alphabet"` usually you need to stop through the code which is less fun

**Comment by prince-chrismc** [comment]
I opened a PR to that it will be easier to print the claims for Boost. #251

I would also like to break a separate issue for having more feedback in the errors of base64 decoding, is that good for everyone?
