### ISSUE TITLE
Checking roles

### ISSUE THREAD

**Issue by eric72** [Thalhammer/jwt-cpp#28]
Hi,

I would like to know, how you can check the roles taken in the payload, roles is an attribut who look like this : ["myRole1", "myRole2"]...
Maybe there already a method ready like for with_issuer().

Thanks for your help, i  think it can help many people.

**Comment by Thalhammer** [comment]
I assume you want to make sure all of the roles you specify are present in the jwt?

There is no support for custom verification functions, however there have been thoughts about implementing something like that before.
You will have to check the content of the variable after you verified the token.
Example:
```c++
auto roles = decoded.get_payload_claim("roles").as_set();
std::set<std::string> required_roles = {"myRole1", "myRole2", "myRole3"};
for(auto & r : required_roles) {
	if(roles.count(r) == 0) {
		// Role missing
		// Fail the verification
	}
}
// Everything is fine
```

**Comment by eric72** [comment]
No, just if one of thoses roles is on the jwt

**Comment by eric72** [comment]
I post the solution here, like this you will get both solution, yours and mine.
In case of you want to check if your user got the right role, you can do this:

bool right = false;
auto roles = decoded_token.get_payload_claim("roles").as_set();
std::set<std::string> required_roles = { "myRole1", "myRole2", "myRole3" };

for (auto & required_role : required_roles) { //On récupère tout les éléments du tableau
	for (auto & role : roles) {

	      if (required_role == role) {
		     right = true;
	      }

	}
}
if (right == false) {
	// Role missing
	// Fail the verification
       //  Your user don't have the right to access to this API for exemple
}
