### ISSUE TITLE
Google JWT

### ISSUE THREAD

**Issue by okotik** [Thalhammer/jwt-cpp#281]

**Comment by prince-chrismc** [comment]
What happened?
A bug happened!I try decode Google JWT and error is
"terminate called after throwing an instance of 'std::runtime_error'
what(): Invalid input: too much fill"

How To Reproduce?
std::string token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjU5NjJlN2EwNTljN2Y1YzBjMGQ1NmNiYWQ1MWZlNjRjZWVjYTY3YzYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIyNjExNDU5OTAyNzEtaWdiY3RraHVzMjJhMDZxOWIwdHU2OWZuNHJzYW5pdjEuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiIyNjExNDU5OTAyNzEtaWdiY3RraHVzMjJhMDZxOWIwdHU2OWZuNHJzYW5pdjEuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDIzMDA0OTYwMzA4ODc5NTU2MTIiLCJlbWFpbCI6InpidXQubGlua3NAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF0X2hhc2giOiJvRGl3VVZrcE1PSmpNOTB2VWlEUVRRIiwibmFtZSI6ItCe0YDQtdGB0YIg0J7RgNC10YHRgiIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BR05teXhZU0hrNVQxTE50enl4TjVwdmlRVjFlT0NFTkxYcHg3R0JFN29SQj1zOTYtYyIsImdpdmVuX25hbWUiOiLQntGA0LXRgdGCIiwiZmFtaWx5X25hbWUiOiLQntGA0LXRgdGCIiwibG9jYWxlIjoidWsiLCJpYXQiOjE2NzcyNjA4ODgsImV4cCI6MTY3NzI2NDQ4OH0.LNg0v0VZ-WBrr8jlPoL2Yjr3lgWvCSm2caqsKDwdiomv4s_Z5Wkui9_7gOnHjnDWM7TDm2-YXrWYRSWum50x1huBpKQCqUzDesufwAyQHrRGEcKr1NHWWq4C78arrc8hRa0iUQYmGSRY5TOWXoslbHICO5a9Fze3IYE7yjj3MOdQHM529z7Eh99GyrgzQV_ELXKmT_ssrHuLxHRsfuGcsf59y-uFs7F6IlEWXYfUv9TeMF8lIKy490_Tky9cBF98vpCgiiMhvNTlcDHX8VOYjOvVXoPBeCA9jwZStLc4mcM96AdsVWx7GJLrRLVOy9izdvm7Byo0t81O7msWbeaQZ";
auto decoded = jwt::decode(token);

Version
0.6.0

What OS are you seeing the problem on?
Windows

What compiler are you seeing the problem on?
MSVC

Relevant log output
No response

**Comment by prince-chrismc** [comment]
Feel free to reopen if you have more information
