### ISSUE TITLE
Google jwt

### ISSUE THREAD

**Issue by okotik** [Thalhammer/jwt-cpp#282]
### What's your question?

I want verify google jwt

### Additional Context
My google JWT "eyJhbGciOiJSUzI1NiIsImtpZCI6ImQyNWY4ZGJjZjk3ZGM3ZWM0MDFmMDE3MWZiNmU2YmRhOWVkOWU3OTIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIyNjExNDU5OTAyNzEtaWdiY3RraHVzMjJhMDZxOWIwdHU2OWZuNHJzYW5pdjEuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiIyNjExNDU5OTAyNzEtaWdiY3RraHVzMjJhMDZxOWIwdHU2OWZuNHJzYW5pdjEuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDIzMDA0OTYwMzA4ODc5NTU2MTIiLCJlbWFpbCI6InpidXQubGlua3NAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF0X2hhc2giOiJTR3pIUWxpUEZlVzlaODBHVEZzS1NnIiwibmFtZSI6ItCe0YDQtdGB0YIg0J7RgNC10YHRgiIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BR05teXhZU0hrNVQxTE50enl4TjVwdmlRVjFlT0NFTkxYcHg3R0JFN29SQj1zOTYtYyIsImdpdmVuX25hbWUiOiLQntGA0LXRgdGCIiwiZmFtaWx5X25hbWUiOiLQntGA0LXRgdGCIiwibG9jYWxlIjoidWsiLCJpYXQiOjE2Nzc0OTQ5NzgsImV4cCI6MTY3NzQ5ODU3OH0.Cyhcs1QOl0JFTwAbecE7zUSBYDdWxeuQgD1bA264o7btryNFvq22l6I799TDcpwwX0qQZSwHnHfWzvGtn-XiBhs6C3XYboFP94ugIvi1YBx-7ZYnE4Z1-HxnBIz5qjy-bW4ESj9DXFM9QTUBwp0ejH0vhRIYDKa48SVl0qbJanRoY-BDhuTaoogME0r_NWGleuyJ_lIv-EUgAdq5Oottm-ahfbcX6I1dYKEjjAINabROeUWn6UTvPJOrDmRjwCXsQVoMcjdjp4QuQceRYZtUMCtldFIg2UCa9Q2luII3UDzB8E8kMKdZPRgV0vpAxe_ueKdYx9xVATIvXUpWmINjTg"
Hello. I want verify google JWT with some of this keys https://www.googleapis.com/oauth2/v3/certs or CERTIFICATES https://www.googleapis.com/oauth2/v1/certs
How can I do this?

**Comment by prince-chrismc** [comment]
You need to make an RSA with it #271 should give you some leads :) the links point to code examples

**Comment by okotik** [comment]
ok. thank you
