### ISSUE TITLE
Exception-free?

### ISSUE THREAD

**Issue by Bolderaysky** [Thalhammer/jwt-cpp#294]
### What would you like to see added?

Build with `-fno-exceptions`

### Additional Context

I'm developing project with disabled exception handling and I had some thoughts on using this lib for JWT, but it looks like this `jwt-cpp` make use of exceptions for error handling. 
What do you think about adding ability to disable exception handling, for example, through preprocessor definition, something like `JWT_NO_EXCEPTIONS`, which would change model of error handling? 
Also, this can be beneficial as this change would allow to build and use this lib on microcontrollers (not sure about using openssl in such case, but wolfssl mostly should handle such cases and as far as I know it's supported).

**Comment by Bolderaysky** [comment]
Ahhh, sorry, found that exceptions come from json libraries used and picojson has `PICOJSON_NOEXCEPT` definition. Closing this as it was not an issue at all.

**Comment by prince-chrismc** [comment]
There are code paths with exceptions which are mostly available, however it would be great to see more of the API update to use `error_code`
