### ISSUE TITLE
c++20 undefined behavior usage

### ISSUE THREAD

**Issue by lirik90** [Thalhammer/jwt-cpp#300]
### What happened?

Hi. It's can't be compiled with this command:
```bash
g++ -std=c++20 -fsanitize=undefined test.cpp
```

Problem in line 86 file include/jwt-cpp/base.h
```c++
static std::initializer_list<std::string> fill{"%3D", "%3d"};
```

### How To Reproduce?

```c++
#include <jwt-cpp/traits/kazuho-picojson/defaults.h>
int main() {
  return 0;
}
```

### Version

0.6.0

### What OS are you seeing the problem on?

Linux

### What compiler are you seeing the problem on?

GCC

### Relevant log output

```shell
[kirill@main-pc test]$ g++ -std=c++20 -fsanitize=undefined ~/test.cpp 
In file included from /jwt-cpp/include/jwt-cpp/jwt.h:12,
                 from /jwt-cpp/include/jwt-cpp/traits/kazuho-picojson/traits.h:12,
                 from /jwt-cpp/include/jwt-cpp/traits/kazuho-picojson/defaults.h:4,
                 from /home/kirill/test.cpp:2:
/jwt-cpp/include/jwt-cpp/base.h: In static member function «static const std::initializer_list<std::__cxx11::basic_string<char> >& jwt::alphabet::helper::base64url_percent_encoding::fill()»:
/jwt-cpp/include/jwt-cpp/base.h:86:100: ошибка: «(((const std::__cxx11::basic_string<char>*)(& <temporary>)) != 0)» не есть константное выражение
   86 |                                         static std::initializer_list<std::string> fill{"%3D", "%3d"};
      |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prince-chrismc** [comment]
Create a test for the undefined sanitizer

**Comment by sjanel** [comment]
This is because `std::initializer_list` is a proxy object that should not be used as a storage. It could be replaced with a standard array.

The issue can be fixed like [this](https://github.com/Thalhammer/jwt-cpp/pull/275/files#diff-7884d932b55bcb4b9bbf516c2f3f7e55624c0dfdf8656783ec42c8d3d694db5eR113)
