### ISSUE TITLE
Release status of 0.7.0-rc.0

### ISSUE THREAD

**Issue by rodgreennc** [Thalhammer/jwt-cpp#314]
### What's your question?

Why is 0.7.0-rc.0 still marked as pre-release

### Additional Context

A product I suport for my company is examining our 3rd party libraries and making sure we have latest releases.  When I look at jwt-cpp, I see there is a version 0.7.0-rc.0, but that it is still marked as pre-release and there has not been a formal "latest release" since 0.6 11 months after the 0.7.0-rc.0 has been released.
We typically would move to a newer version but I question whether we should given that it is still marked pre-release.
Will there be a formal release of this code?

**Comment by prince-chrismc** [comment]
Super excited to learn about a new user using this in real code :) so thank you!

It has been brought up but we are a small team of maintainers and haven't had the chance to finalize it.
See https://github.com/Thalhammer/jwt-cpp/pull/299. That tag should never change. When 0.7.0 is made it will be against the latest code in master.

I personally am relocating to a different country as my work visa expired and will need to find new employment.

It may be several months before the release but rest assured it's "next" on the agenda for the project.

**Comment by rodgreennc** [comment]
Thanks for your feedback.  We will likely stick with 0.6.0 release and then upversion when you release 0.7.0

Best of luck in your move and job search.

**Comment by prince-chrismc** [comment]
https://github.com/Thalhammer/jwt-cpp/releases/tag/v0.7.0 Now exists 😄
