### ISSUE TITLE
How to use payload and get the payload data

### ISSUE THREAD

**Issue by manishjha5410** [Thalhammer/jwt-cpp#338]
### What's your question?

How to use payload and get the payload data in jwt

### Additional Context

Hi @Thalhammer there is no documentation to use payload data please help if you can

**Comment by manishjha5410** [comment]
Also why this error is running around da function:
 error: conversion from ‘jwt::builder<jwt::traits::kazuho_picojson>’ to non-scalar type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} requested
  267 |                 std::string token = jwt::create()
      |                                     ~~~~~~~~~~~~~                          
  268 |                                                         .set_issuer("auth0")
      |                                                         ~~~~~~~~~~~~~~~~~~~~
  269 |                                                         .set_type("JWT")
      |                                                         ~~~~~~~~~~~~~~~~   
  270 |                                                         .set_id(jti)
      |                                                         ~~~~~~~~~~~~       
  271 |                                                         .set_key_id("internal-gateway-jwt.api.sc.net")
      |                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  272 |                                                         .set_subject("jwt-cpp.example.localhost")
      |                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  273 |                                                         .set_issued_at(std::chrono::system_clock::now())
      |                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  274 |                                                         .set_expires_at(std::chrono::system_clock::now() + std::chrono::seconds{36000})
      |                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  275 |                                                         .set_payload_claim("sample", jwt::claim(std::string{"test"}));
      |                                                         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/app.out.dir/build.make:132: CMakeFiles/app.out.dir/BACKEND/User/User.cpp.o] Error 1

**Comment by prince-chrismc** [comment]
You should not be using the Payload directly rather we provide a very customizable `verifier` https://thalhammer.github.io/jwt-cpp/classjwt_1_1verifier.html#a9ad51170089fb1566c5d97314cc33e41 you can see the various examples to validating claims.

If there is something specific you are trying to do please provide more information with a polite tone :)

**Comment by manishjha5410** [comment]
So sorry for my tone i had a very bad day and unable to solve the issue from last week please apologies for the work thanks i am closing this iisue

**Comment by manishjha5410** [comment]
One last thing i forgot to ask but how would i get the payload data in this we can use the verifier to verify but my use case is like i want to get the data from jwt Token

**Comment by prince-chrismc** [comment]
https://thalhammer.github.io/jwt-cpp/classjwt_1_1decoded__jwt.html#a6a86e22661351e17f8880d6b4801ea9a

There's a few helpers on the decoded token :) you can get individual claims or the entire JSON object.

**Comment by prince-chrismc** [comment]
Please provide a reproducible examples with code and build scripts if applicable. A brief description of the workflow is also important.

Please refer to the various verify examples that are provided. Heres the one for RSA
 https://github.com/Thalhammer/jwt-cpp/blob/bd682eddba5b5fd56718a9cc13dfe2723b2986cd/example/rsa-verify.cpp#L28

**Comment by prince-chrismc** [comment]
Please open a new issue with more details as this is a different topic :)
