### ISSUE TITLE
How to verify a jwt

### ISSUE THREAD

**Issue by manishjha5410** [Thalhammer/jwt-cpp#340]
### What's your question?

How to verify a jwt

### Additional Context

As you can seen in the image there is an arrow for red mark which state as verified and int the blue mark there is field for Hmac hash  which i got from https://jwt.io/
![imageedit_4_4287978288](https://github.com/Thalhammer/jwt-cpp/assets/69567616/ca6798a9-f763-4c5e-8f7f-0047c5ca2790)

Is there any way to verify the signature in the current application, i got one of the solution from [prince-chrismc] where i suggested to use 
![Screenshot from 2024-04-12 09-01-47](https://github.com/Thalhammer/jwt-cpp/assets/69567616/a12449d4-301c-4f4a-bbf3-dc8efe272679)
but in this example the verifier just verify the token but how could i know that the token is verified ?

**Comment by Thalhammer** [comment]
`verifier.verify(token);` throws an exception when theres something wrong with the token. This includes things like wrong issuer, expired tokens as well as invalid signatures. You can either catch that exception and turn it into a simple bool return or use the `std::error_code` overload and check that.

**Comment by manishjha5410** [comment]
Okay buddy i am closing this issue
