### ISSUE TITLE
Invalid input: not within alphabet

### ISSUE THREAD

**Issue by TheCardinalSystem** [Thalhammer/jwt-cpp#341]
I am trying to decode a JWT so I can verify it, but I keep getting a verification exception with the message "Invalid input: not within alphabet". Here is how to reproduce:

```cpp
std::string token = "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjYXV0aDAiLCJleHAiOjE3MTMzODgxNjgsInN1YiI6InRlc3RfdXNlciJ9.dlAk0mSWk1Clzfi1PMq7Omxun3EyEqh-AAu-fTkpabA67ZKenawAQhZO8glY93flukpJCqHLVtukaes6ZSOjGw";
jwt::decoded_jwt<jwt::traits::nlohmann_json> decoded(token);
```

I verified the token's integrity [here](https://jwt.io/#debugger-io?token=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjYXV0aDAiLCJleHAiOjE3MTMzODgxNjgsInN1YiI6InRlc3RfdXNlciJ9.dlAk0mSWk1Clzfi1PMq7Omxun3EyEqh-AAu-fTkpabA67ZKenawAQhZO8glY93flukpJCqHLVtukaes6ZSOjGw).

**Comment by prince-chrismc** [comment]
I was able to build the code example you provided. You'll need to provide more information 🤔 you might want to double check how you are receiving and extract the token

https://github.com/prince-chrismc/jwt-cpp/actions/runs/8731222077/job/23956285054?pr=40#step:9:135

**Comment by Thalhammer** [comment]
> Invalid input: not within alphabet

This is a error thrown by the base64 decoding. Make sure you are passing a valid token.

**Comment by TheCardinalSystem** [comment]
> I was _not_ able to reproduce the problem with the code example you provided. You'll need to provide more information 🤔 you might want to double check how you are receiving and extract the token
> 
> https://github.com/prince-chrismc/jwt-cpp/actions/runs/8731222077/job/23956285054?pr=40#step:9:135

Interesting. It works with a string literal, but the same token fails when it's provided via IP packet. It looks like there's nothing wrong with your code, so I will investigate my own code further.

**Comment by Thalhammer** [comment]
> but the same token fails when it's provided via IP packet.

Make sure you don't have extra bytes at the front or back of the string. The base64 decoding doesn't run strlen, it relies on the string you give it. If you have a nullbyte at the end it will give that error but the byte won't show in e.g. a terminal.

**Comment by TheCardinalSystem** [comment]
> > but the same token fails when it's provided via IP packet.
> 
> Make sure you don't have extra bytes at the front or back of the string. The base64 decoding doesn't run strlen, it relies on the string you give it. If you have a nullbyte at the end it will give that error but the byte won't show in e.g. a terminal.

I think it's an issue with the C++ 11 standard library. Take a look at my GDB output:

```
Thread 45 "connection" hit Breakpoint 1, jwt::base::details::pad (base="73zr0EUBnjN3C8omv7jZ-Exn3EzUHMG6ZuGuCNmpjEbZPvRjzItEXcZflyx4PiPbE1pVSxWriQyAT0B1urbn-Q", fill="%3d") at /usr/local/include/jwt-cpp/base.h:243
243                                     return base + padding;
(gdb) s
std::operator+<char, std::char_traits<char>, std::allocator<char> > (__lhs="73zr0EUBnjN3C8omv7jZ-Exn3EzUHMG6ZuGuCNmpjEbZPvRjzItEXcZflyx4PiPbE1pVSxWriQyAT0B1urbn-Q", __rhs="%3d") at /usr/include/c++/11/bits/basic_string.h:6098
6098          basic_string<_CharT, _Traits, _Alloc> __str(__lhs);
(gdb) fin
Run till exit from #0  std::operator+<char, std::char_traits<char>, std::allocator<char> > (__lhs="73zr0EUBnjN3C8omv7jZ-Exn3EzUHMG6ZuGuCNmpjEbZPvRjzItEXcZflyx4PiPbE1pVSxWriQyAT0B1urbn-Q", __rhs="%3d")
    at /usr/include/c++/11/bits/basic_string.h:6098
0x00007fffe8901b06 in jwt::base::details::pad (base="73zr0EUBnjN3C8omv7jZ-Exn3EzUHMG6ZuGuCNmpjEbZPvRjzItEXcZflyx4PiPbE1pVSxWriQyAT0B1urbn-Q", fill="%3d") at /usr/local/include/jwt-cpp/base.h:243
243                                     return base + padding;
Value returned is $2 = "73zr0EUBnjN3C8omv7jZ-Exn3EzUHMG6ZuGuCNmpjEbZPvRjzItEXcZflyx4PiPbE1pVSxWriQyAT0B1urbn-Q\000%3d"
(gdb)
```
There is clearly a null-terminator being added by the standard library (when it was not present before).

**Comment by prince-chrismc** [comment]
Glad we could help!
