### ISSUE TITLE
Claim class constructor

### ISSUE THREAD

**Issue by AngryLemonn** [Thalhammer/jwt-cpp#35]
Hi,

I have been using this library for a while, and I do not understand why the claim class has not a constructor for an array of numbers (int, int64, double, etc). The type of the claim can be an array, but only an array of strings.  Is for some reason that I do not understand?

Regards,
J. A.

**Comment by Thalhammer** [comment]
The "string list" constructor is in fact a set constructor (i.e. no duplicates), but you are right, a claim can be an array.
