### ISSUE TITLE
Linker error for OpenSSL on Windows

### ISSUE THREAD

**Issue by gggamemaster** [Thalhammer/jwt-cpp#350]
### What's your question?

what verison openssl should i use?

### Additional Context

i download jwt-cpp using vcpkg,and i get 
![image](https://github.com/Thalhammer/jwt-cpp/assets/25485742/158b402c-589c-4757-81d9-c0d8c22752b0)
and i compile the openssl 1.0.1，i get 
![image](https://github.com/Thalhammer/jwt-cpp/assets/25485742/cb315668-3507-41b4-8d15-1b897ec643f6)
header folder 
![image](https://github.com/Thalhammer/jwt-cpp/assets/25485742/3076a747-be0b-4667-ab97-f2d85d0b72d7)
lib folder 
![image](https://github.com/Thalhammer/jwt-cpp/assets/25485742/2b3737e6-a131-40b0-ad07-1df5e8448be5)
and i write a test function 
![image](https://github.com/Thalhammer/jwt-cpp/assets/25485742/47ca9411-45c6-406a-94ed-a776a7508872)
my project setting：
header folder：
![image](https://github.com/Thalhammer/jwt-cpp/assets/25485742/57ba81e5-e2ba-4a8f-a9df-f43695647544)
lib dir：
![image](https://github.com/Thalhammer/jwt-cpp/assets/25485742/8e3404b4-d4d6-4914-8cbf-7712fe2aa867)
and i have join the lib libeay32.lib and ssleay32.lib to project，when i complile code，meet error  error LNK2019: 无法解析的外部符号 _BIO_new，loos like i do not link the lib。what should i do?

**Comment by Thalhammer** [comment]
jwt-cpp supports all versions of openssl between 1.0.x and 3.x, so your while your version is on the older end (you should really use a recent one in the name of security) I think it should work fine.

I don't speak whatever language that is, but LNK**** errors usually mean that something with your linker setup is wrong. You have added the openssl path, however you also need to make sure you add the relevant libraries to the linker.

**Comment by gggamemaster** [comment]
if i use the right version of openssl,the lib after i compile the source code ,will generate lib libssl.lib and libcrypto.lib insteal of  libeay32.lib and ssleay32.lib,am i right?i have compile the openssl and i get libeay32.lib and ssleay32.lib, it look like i use the wrong version of openssl

**Comment by prince-chrismc** [comment]
It's seems you have misused vcpkg. You have installed openssl with vcpkg and a second older copy manually?

So it not surprising you see different versions at link or runtime.

I would highly recommend using CMake and VCPKG together to install dependencies so you'll don't have conflicts in your system

**Comment by prince-chrismc** [comment]
@gggamemaster if you've passed this issue please close it :)

**Comment by gggamemaster** [comment]
i have passed it after reinstall openssl
