### ISSUE TITLE
unexpected exception(expired) throws in verify JWT token

### ISSUE THREAD

**Issue by quanchentg** [Thalhammer/jwt-cpp#354]
### What's your question?

unexpected exception(expired) throws in verify JWT token

### Additional Context

Fist of all, very appreciate for jwt-cpp, it is awesome!

i have a function called validateJWTtoken(jwttoken)

before start using 

`
try {
   verifier.verify(decoded_token);
} catch (const jwt::error::token_verification_exception& ex) {
   ....
}
`
i have a expiration check such as

`
  if (expiration_time <= seconds_since_epoch) {
      ...
    }
`

the strange thing is 
the jwt token passed in this function can always pass my expiration check
but sometimes (very random) failed in the verifier.verify(decoded_token) and throws token expired exception.

could you please give me some clue on it? Thank you.

**Comment by quanchentg** [comment]
nvm, i figure it out.

**Comment by prince-chrismc** [comment]
> very appreciate for jwt-cpp, it is awesome!

Thanks!
