### ISSUE TITLE
Add bool to verify()

### ISSUE THREAD

**Issue by dwampler35** [Thalhammer/jwt-cpp#355]
### What would you like to see added?

Add a return value to verify()

### Additional Context

Can we add a bool as a return code for verify()?   It's not appropriate to use exceptions in all environments to handle failures.

**Comment by Thalhammer** [comment]
> It's not appropriate to use exceptions in all environments to handle failures

You don't have to use exceptions, the verify method provides [a overload](https://github.com/Thalhammer/jwt-cpp/blob/a6927cb8140858c34e05d1a954626b9849fbcdfc/include/jwt-cpp/jwt.h#L3551) that accepts a `std::error_code` which gets filled with details about the verification error. If you provide a error code the verify method won't throw (except for truly exceptional circumstances like OOM).

Ideally you should check the reason the verification failed and give the provider of the token a hint on what went wrong, but if all you care about is a true/false result you can simply use `std::error_code`'s [operator bool](https://en.cppreference.com/w/cpp/error/error_code/operator_bool) to check for errors (true meaning an error occurred).

I hope this clarifies your issue.

**Comment by dwampler35** [comment]
Thanks I missed that overload
