### ISSUE TITLE
Can jwt::builder::sign() be const?

### ISSUE THREAD

**Issue by nerd-of-paridise** [Thalhammer/jwt-cpp#37]
It would be nice if the `std::string jwt::builder::sign(const T& algo)` method could be `const`.

From what I can determine, the only reason that it is not `const` is that `set_algorithm()` is being called to set the 'alg' claim.

Is there any reason that the 'alg' claim cannot be added directly to `obj_header` instead of modifying `this`?

Am I missing some design element?

**Comment by Thalhammer** [comment]
No this is indeed a simple oversight.
