### ISSUE TITLE
Header only - editor error

### ISSUE THREAD

**Issue by nicraMarcin** [Thalhammer/jwt-cpp#40]
Hello, I have problem with basic usage

![PrintScreen2019-09-16 21-52-15](https://user-images.githubusercontent.com/1545069/64988711-61f6c100-d8cc-11e9-9e14-7bb0fedbd219.png)

What's wrong?

**Comment by nicraMarcin** [comment]
This worked for me
```
std::string TokenSecurity::createToken()
{
    jwt::claim value(std::string("Test"));
    
      auto token = jwt::create()
            .set_type("JWS")
            .set_payload_claim("sample", value)
            .set_issued_at(std::chrono::system_clock::now())
            .set_expires_at(std::chrono::system_clock::now() + std::chrono::seconds{3600})
            .sign(jwt::algorithm::hs512{"secret"});

    return token;
}
```

**Comment by Thalhammer** [comment]
@nicraMarcin The problem you faced is the fact that the constructor of "claim" is explicit.
You can pass `-DJWT_CLAIM_EXPLICIT=0` on the commandline and add this define to your editor to override the default and make them not explicit.

**Comment by nicraMarcin** [comment]
@Thalhammer thanks for hint.
