### ISSUE TITLE
Api referece - documentation

### ISSUE THREAD

**Issue by nicraMarcin** [Thalhammer/jwt-cpp#41]
Where can I find some api referece and some examples? for example: how to use with rsa public and private key

**Comment by Thalhammer** [comment]
Currently the only documentation are the example in README.md and the various testcases in *Test.cpp

**Comment by nicraMarcin** [comment]
:(

**Comment by Thalhammer** [comment]
I almost forgot about it, but most of the methods are commented with doxygen comments and there is a doxygen config in the root. It's not really a complete documentation, but it might help.

**Comment by paulotovo** [comment]
Hello Thalhammer,

I have seen on several sites about the header "typ" parameter that must be configured as JWT.
For example: "typ" : "JWT"
But on RFC says:
"The "typ" (type) Header Parameter defined by [JWS] and [JWE] is used
   by JWT applications" and " If present, it is RECOMMENDED that
   its value be "JWT" to indicate that this object is a JWT."

In your examples you use "typ" : "JWS".

What would be the difference? What would be the correct use?

Thanks.

Best Regards

Paulo

**Comment by Thalhammer** [comment]
@paulotovo According to the rfc that part is optional and should not be used by the jwt library.
It defines the media type and could be used to disabiguate if you expect not only jwt tokens to hit your app. JWT stands for Json Web Tokens and JWS for Json Web Signature which is a different, but very similar rfc. In 99% of cases it does not matter and the reason my test token uses JWS is simply a coincidence.

**Comment by minjax** [comment]
Continuing with the theme of API documentation/examples, the example given shows get_payload_claims() in this context:
```
      std::string token = "eyJhbGciOiJIUzI1...OkEE";
      auto decoded = jwt::decode(token);

      for( auto& e : decoded.get_payload_claims() )
          std::cout << e.first << " = " << e.second.to_json() << std::endl;
```
but, I don't find any definition of get_payload_claims() in class jwt::decoded_jwt<jwt::picojson_traits> or otherwise...

What am I missing here?

Thanks,

**Comment by prince-chrismc** [comment]
The current master is a getting ready for an release candidate, and rightfully so because it seem like `get_payload_claims` got removed during #71 by accident :fearful: 

I would **strongly** recommend using the v0.4.0 release while the last few details get ironed out. ( I am using that in production code ) The method in question is available there.

https://github.com/Thalhammer/jwt-cpp/blob/34bb0644ea613cfcbc09c148db9de8aa6c5612b5/include/jwt-cpp/jwt.h#L1027

Sorry for the inconvience!
