### ISSUE TITLE
signature verification failed

### ISSUE THREAD

**Issue by Rad1685** [Thalhammer/jwt-cpp#42]
Hi, I have an need to verify the token generated through JAVA API in C++ jwt verification. Now the issue is, the signature generated in C++ and JAVA are different when using the same algorithm, data and secret code.

Can anyone let me know if we have issue verifying the token generated in two different programming languages.

“alg”: “HS512”
“name”: “Test”
secret key = “12345678901234567890”

Thanks in advance

**Comment by Thalhammer** [comment]
Normally they should be exactly the same.
Can you provide a test token or make sure it verifies correctly in the debugger [here](https://jwt.io)?

**Comment by Rad1685** [comment]
Thank you for your immediate reply. Please find the token generated in Java and C++.
“alg”: “HS512”
“name”: “Test”
secret key = “12345678901234567890”

Token generated in Java 
eyJhbGciOiJIUzUxMiJ9.eyJuYW1lIjoiVGVzdCJ9.K5zOyuT9njBNWPttoQLDEKIQFaiGs4URM7vN90DXtsqL8NKIqU8UNT3RNJXCUKnaRr5hQvSvaz9huxuj8jwYlA

For the same data, the token generated in C++
eyJhbGciOiJIUzUxMiJ9.eyJuYW1lIjoiVGVzdCJ9.9LuJlX6wVlXJ8u_C3GsGyLaMiwufc17XzA-kYcbRFyeLmS4TVG2iQvw_sOpby5dOHz2sx3K2hsWHRxLaP-f1zA

Regards,
Rad

**Comment by Thalhammer** [comment]
As you can check on the official jwt website, your Java token is invalid.
What library do you use in Java?

**Comment by Rad1685** [comment]
The java token gets verified successfully on checking the base64 checkbox. Also the C++ token also verifies successfully only after checking the checkbox.

**Comment by Rad1685** [comment]
Thank you very much for your inputs. As you mentioned the issue was with java API. Now signature is verified successfully.

Thanks & Regards,
Rad

**Comment by Thalhammer** [comment]
No Problem.
