### ISSUE TITLE
Not working when compiled but working on visual studio

### ISSUE THREAD

**Issue by eric72** [Thalhammer/jwt-cpp#43]
Hi,

Maybe you know where my problem come from, the verification for the token work when i test on visual studio, but then, when i've compiled and test from the compiled code, the token is always false.

Maybe some missed links for the compiled code and the function return an error or something ?
Thanks for you help.

**Comment by eric72** [comment]
I think i need to make a dll of it on my release folder

**Comment by Thalhammer** [comment]
You cant build a dll of jwt-cpp, as its header only.
However it uses OpenSSL under the hood, so make sure a correct openssl dll is present in your library path and release folder. I don't use Visual Studio (or Windows) so I'am not sure if I am of much help.
You could try to print the exception message and see if it gives any clue.

**Comment by eric72** [comment]
you mean an openssl.dll ?
On windows it's a openssl.dll

**Comment by Thalhammer** [comment]
Unless you linked your project against a static build of openssl (which is not the default as far as I know) there should be an openssl.dll somewhere.

**Comment by eric72** [comment]
And on Linux, you don't have this problem ?
Just use the .h and it can compile ?
Because i would like to compile for linux too

**Comment by Thalhammer** [comment]
On linux you also need to link against openssl but almost every linux system has it installed and unlike windows you dont need a copy of the dll per programm but it uses one per system. So its much less of a problem.

**Comment by eric72** [comment]
I've tried many thing but, my project work only from Visual Studio, but when i start it from the exe it doesn't work, i don't understand why, i tested why nuget too, and linked some lib manually but it's the same

**Comment by Thalhammer** [comment]
@eric72 Is there some kind of error message or something the like.

**Comment by eric72** [comment]
"failed to load public key: PEM_read_bio_PUBKEY failed"

but it's working fine when i compile with Visual Studio

**Comment by Thalhammer** [comment]
@eric72 Are you sure it is actually compiled correctly ?
If you load the key from a file, are you sure its read correctly.

**Comment by eric72** [comment]
Oh man you right, i found the problem thanks my friend i was focus somewhere else

**Comment by Thalhammer** [comment]
No problem, I am happy to help :)
