### ISSUE TITLE
Error in README.md example

### ISSUE THREAD

**Issue by Lam-Steven** [Thalhammer/jwt-cpp#46]
**Currently says**:
Creating a token (and signing) is equally easy.
```c++
auto token = jwt::create()
	.set_issuer("auth0")
	.set_type("JWS")
	.set_payload_claim("sample", std::string("test"))
	.sign(jwt::algorithm::hs256{"secret"});
```

**Error**:
The _set_payload_claim_ function takes a _jwt::claim_ as its 2nd argument.

**Should say**:
Creating a token (and signing) is equally easy.
```c++
auto token = jwt::create()
	.set_issuer("auth0")
	.set_type("JWS")
	.set_payload_claim("sample", jwt::claim(std::string("test")))
	.sign(jwt::algorithm::hs256{"secret"});
```

**Comment by Thalhammer** [comment]
Thanks for the fix, this went unoticed after claims constructors where changed to be explicit.
