### ISSUE TITLE
Add support for non-JSON payloads

### ISSUE THREAD

**Issue by lrosenthol** [Thalhammer/jwt-cpp#56]
I have a use case where I need to produce a JWT for non-JSON data and it would be nice to be able to use this library to achieve that.

**Comment by lrosenthol** [comment]
I've looked at the code and seems pretty straight-forward to create another version of the sign() method to support that case...I'll look into submitting a PR

**Comment by Thalhammer** [comment]
Note that tokens generated with this would not be standardscompliant and you basically removed all features of JWT.
If all you want to do is sign and verify random payloads you can skip the jwt parts and directly use the algorithms. They all follow the same interface and are binarysafe, so you can pass whatever your payload is.

**Comment by lrosenthol** [comment]
They wouldn't be valid JWT - that is true.  They would be valid JWS in Compact Serialization, which is what I am trying to achieve.   Granted, that's taking your library a bit off the original goal, but I think it's perfectly reasonable.  (and I've done this in a fork if you want to see)

**Comment by lrosenthol** [comment]
Changes are in my branch at https://github.com/lrosenthol/jws-jwt-cpp

**Comment by Thalhammer** [comment]
Did you verify the token in some other library ?
Because if I understood the spec correctly, then the payload is included in the signature (in detached mode) but not in the token.

**Comment by lrosenthol** [comment]
If you think about it as a detached JW Signature and not a token, yes, it works fine - provided that both sides have apriori agreement on what the payload should be.  In my case, it's an image that goes along with the JWS bytes.

**Comment by prince-chrismc** [comment]
This seems to be out of the scope for the project, the majority of JWT use the JWS JSON Serialization.
