### ISSUE TITLE
Error building project

### ISSUE THREAD

**Issue by blongho** [Thalhammer/jwt-cpp#57]
I have included this library into my project via CMake like this
 1. `include_directories(../common/modules/jwt-cpp-0.3.1/include) # Json Web Token (library)`
2. In header file
```
#include <jwt-cpp/jwt.h>  // jwt
#include <iostream>
```
I tried to build the project using the example code 
```
auto token = jwt::create()
	.set_issuer("auth0")
	.set_type("JWS")
	.set_payload_claim("sample", jwt::claim(std::string("test")))
	.sign(jwt::algorithm::hs256{"secret"});
```
As well not having any code at all in my encryption method 
```
std::string DataProtector::encrypt(const std::string& input)
{
    auto key = "secret"; //Secret to use for the algorithm
  //Create JWT object

    //Get the encoded string/assertion
    return "";
}
```
In both cases, i get this. 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2665	'std::unique_ptr<BIO,void (__cdecl *)(BIO *)>::unique_ptr': none of the 2 overloads could convert all the argument types	work	C:\Users\work\Documents\workspace\SDK\common\modules\jwt-cpp-0.3.1\include\jwt-cpp\jwt.h	81
```	

My setup:
OS: Windows 10
IDE: Visual Studio Community 2019 version Version 16.4.5

What should i do to make this work?

**Comment by Thalhammer** [comment]
What version of OpenSSL are you using ?
Is your project configured to use at least C++11 ?
Can you post the full error message ?

**Comment by blongho** [comment]
I am using openssl version: 0x1000115fL
Yes, my project is configured to used C++17 
``Makefile 
set_property(TARGET ${LIB_TARGET_NAME} PROPERTY CXX_STANDARD 17)
```
About the error log, it is unfortunate that i can not provide it now. I had to look elsewhere for another solution.

**Comment by Thalhammer** [comment]
We have a switch because the signature of an OpenSSL function changed.
Turns out we seem to have missed the correct version it changed.
Can you try to change the line 78 in jwt.h from
`#if OPENSSL_VERSION_NUMBER <= 0x1000114fL`
to
`#if OPENSSL_VERSION_NUMBER <= 0x10100004L`
and check if it compiles fine with it ?

**Comment by prince-chrismc** [comment]
@Thalhammer I pretty sure it's `0x10100003L`

[the blame](https://github.com/openssl/openssl/blame/e7fb44e7c3f7a37ff83a6b69ba51a738e549bf5c/crypto/bio/bss_mem.c#L86) points to this commit https://github.com/openssl/openssl/commit/8ab31975bacb9c907261088937d3aa4102e3af84. Which the oldest tag was 1.1.0-pre3
