### ISSUE TITLE
How to determine if verification is successful or not?

### ISSUE THREAD

**Issue by BFamzz** [Thalhammer/jwt-cpp#58]
From the code, the following is the way to verify a token.

```
void verify(std::string some_token)
{
	auto verifier = jwt::verify().allow_algorithm(jwt::algorithm::hs256{ "secret" }).with_issuer("auth0");

	verifier.verify(jwt::decode(some_token));
}
```

if this function is called, @Thalhammer , please how can the status of the verification be determined since the function returns a void (because verifier.verify() return void).

Thanks.

**Comment by Thalhammer** [comment]
If you take a look at the test cases or the documentation https://github.com/Thalhammer/jwt-cpp/blob/65b632b674da7fcc189adf7336c652108188aa29/include/jwt-cpp/jwt.h#L1472 you can see that it throws if the verification fails for any reason. The exception might vary depending on the reason of failure, but you know for sure the token is valid if it does not throw.
So you would do something along the lines of this:
```c++
bool verify(std::string some_token)
{
        try {
	       auto verifier = jwt::verify().allow_algorithm(jwt::algorithm::hs256{ "secret"}).with_issuer("auth0");
	       verifier.verify(jwt::decode(some_token));
               return true;
        } catch(const std::exception& e) {
               return false;
        }
}
```
Also note that you can store and reuse a verifier unless the params conditions change. The verifier is designed to do that and it might improve performance.

**Comment by BFamzz** [comment]
Thanks for your response @Thalhammer I understand better. I will close this issue.
