### ISSUE TITLE
Cmake configure with -DEXTERNAL_PICOJSON fails

### ISSUE THREAD

**Issue by duncanmmacleod** [Thalhammer/jwt-cpp#68]
Hi, when building with `-DEXTERNAL_PICOJSON`, my build fails to find the necessary cmake configuration to find the external picojson library:

```console
$ cmake /dev/shm/duncan.macleod/conda/conda-bld/jwt-cpp_1590139493710/work -DBUILD_TESTS:BOOL=TRUE -DCMAKE_INSTALL_PREFIX:PATH=/dev/shm/duncan.macleod/conda/conda-bld/jwt-cpp_1590139493710/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh -DEXTERNAL_PICOJSON:BOOL=TRUE
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: $PREFIX/lib/libcrypto.so (found suitable version "1.1.1g", minimum required is "1.0.2")
CMake Error at CMakeLists.txt:17 (find_package):
  By not providing "Findpicojson.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "picojson",
  but CMake did not find one.

  Could not find a package configuration file provided by "picojson" with any
  of the following names:

    picojsonConfig.cmake
    picojson-config.cmake

  Add the installation prefix of "picojson" to CMAKE_PREFIX_PATH or set
  "picojson_DIR" to a directory containing one of the above files.  If
  "picojson" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "$SRC_DIR/_build/CMakeFiles/CMakeOutput.log".
```

I'm pretty sure `picojson` doesn't provide its own cmake configuration files, so I'm not sure how to proceed (other than patching the build).

**Comment by prince-chrismc** [comment]
This option is primarily for consumers who are using a C++ package manager like Conan which is capable to generating the cmake config for you. I believe vcpkg is capable of it as well 😄

**Comment by Thalhammer** [comment]
There are some system directories which cmake checks for packages. You could simply put a valid cmake configuration there. But really this is something picojson should deal with.
Do you really need to use an external picojson ?
That "build" is only required for the test suite, so just adding the include dir of jwt-cpp to your project should be enough, as it is header only.

**Comment by duncanmmacleod** [comment]
I am investigating build a `conda` package for `jwt-cpp`, and I don't want to end up with a package that bundles `picojson.h`, which is what happens when I _don't_ use the `-DEXTERNAL_PICOJSON` option.

Is there a way to build `jwt-cpp` without bundling `picojson` that doesn't require that option?

**Comment by duncanmmacleod** [comment]
For the record, I understand (and agree) that `picojson` is responsible for providing the `Findpicojson.cmake` file that is required, but the out-of-the-box build for that project doesn't do that.

**Comment by Thalhammer** [comment]
I have never used conda before, but does it normally include and build test cases ?
If not just exclude the picojson file and package only the jwt include directory.

**Comment by duncanmmacleod** [comment]
@Thalhammer, conda (conda-build specifically in this case) is very similar to rpmbuild in how it works: you just specify a shell script that does the build and install and it executes it. It produces a tarball of pre-compiled files that users can install as a dependency of their project. Since `jwt-cpp` is just a header file, I presumed that `cmake --target install` would just install that one header file.

When I execute `make install` from the cmake build I get the following files installed into the prefix:

```
jwt-cpp/jwt-cpp-config.cmake
jwt-cpp/jwt-cpp-config-version.cmake
jwt-cpp/jwt-cpp.cmake
include/jwt-cpp/base.h
include/picojson/picojson.h
include/jwt-cpp/jwt.h
```

Why is `picojson.h` being installed, and how can I stop cmake installing it (short of patching)?

**Comment by Thalhammer** [comment]
You cant, at the moment. However I would happyly accept a pullrequest that adds this feature.
If you want to add it note it here, otherwise I'll add it some time down this week once I come around to do so.

**Comment by duncanmmacleod** [comment]
Since `picojson.h` isn't needed to actually _build_ anything (since nothing in `jwt-cpp` is compiled) I don't see why a this package should require picojson to provide a cmake configuration. Can `EXTERNAL_PICOJSON` be used to just trust that the user has an external copy of `picojson` on their system (i.e. not execute `find_package`)?

**Comment by Thalhammer** [comment]
@prince-chrismc What do you think ?
I have to admit that I dont really use the cmake feature, so I think your opinion might be better here.

**Comment by duncanmmacleod** [comment]
Or perhaps there's a simpler solution, namely that 'binary' package builders (conda, rpm, debian) should ignore the cmake configuration and use just

```bash
install -d ${PREFIX}/include/jwt-cpp
install -p include/jwt-cpp/*.h ${PREFIX}/incude/jwt-cpp/
```

or something like that.

**Comment by prince-chrismc** [comment]
> Since picojson.h isn't needed to actually build anything (since nothing in jwt-cpp is compiled

currently jwt-cpp has a very hard requirement on picojson, you can not use this library without providing picojson. It will not compile downstream by anything that requires this project. It needs to be made available to jwt-cpp.

> I am investigating build a `conda` package for `jwt-cpp`

conda support dependencies, so if you want to make a conda-build for jwt-cpp ( and do not want to bundle picojson; which would be the "right" way ) than you must provide a conda package for picojson as well. Again, hard requirement.

> For the record, I understand (and agree) that `picojson` is responsible for providing the `Findpicojson.cmake` file that is required, but the out-of-the-box build for that project doesn't do that.

I would strongly encourage you to make a contribution to the picojson repository with that contribution :heart:  I personally looked into it but haven't the time to make it. I would be greatly appreciated!

> Can `EXTERNAL_PICOJSON` be used to just trust that the user has an external copy of `picojson` on their system (i.e. not execute `find_package`)?

The reason it's an "external dependencies" is because some _external_ method needs to be used to provide that library, CMake native method is `find_package()` which is why that method is used here.

And yes! you can tell cmake where to search. you may want to read [this](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure) as it provides all the details... you pass the extra flags at configuration

If you contribute a conda build I would expect that it requires/consumes/depends on a picojson conda build as well.

> Or perhaps there's a simpler solution, namely that 'binary' package builders (conda, rpm, debian) should ignore the cmake configuration and use just
> 
> ```shell
> install -d ${PREFIX}/include/jwt-cpp
> install -p include/jwt-cpp/*.h ${PREFIX}/incude/jwt-cpp/
> ```
> 
> or something like that.

If you do this, conda needs to know where picojson is as well. as to come full circle it's a hard requirement

**Comment by duncanmmacleod** [comment]
I understand all of the above, and yes, my plan is to create a conda package for `jwt-cpp` that depends upon a package for `picojson`. I will move forward with my trivial `install` commands for now, since I don't have the cycles right now to figure out the syntax for a cmake config file for picojson.

Thanks for the assistance.

**Comment by Thalhammer** [comment]
@duncanmmacleod This should allow you to disable the install of picojson by setting the cmake option NO_INSTALL_PICOJSON to TRUE.
