### ISSUE TITLE
Use STL implementation over in-house version

### ISSUE THREAD

**Issue by prince-chrismc** [Thalhammer/jwt-cpp#73]
Follow up from #71 

There are several c++17 and fundamentals v2 which have been copied to provide compatible c++11 support.

Type | feature macro | header
---|---|---
`make_void` |  __cpp_lib_void_t (maybe) | <type_traits>
`void_t` | __cpp_lib_void_t | <type_traits>
`nonesuch` | __cpp_lib_experimental_detect | <experimental/type_traits>
`is_detected` | __cpp_lib_experimental_detect | <experimental/type_traits>

Despite this being common practice, we should be checking the feature macro and when available use the STL implementation otherwise fallback to the in house one for compatibility.

The travis matrix should be expanded to test on multiple cppstd versions.

\cc @Thalhammer

**Comment by Thalhammer** [comment]
I have implemented using void_t if available, however as none of my compilers support std::is_detected (yet) I'll post pone this.
