### ISSUE TITLE
Add support for latest algorithms

### ISSUE THREAD

**Issue by prince-chrismc** [Thalhammer/jwt-cpp#79]
There's two new algorithms that have been adopted to the JWT universe, specifically JOSE
- ~[EdDSA](https://tools.ietf.org/html/rfc8037)~
- [ES256K](https://tools.ietf.org/html/draft-ietf-cose-webauthn-algorithms-05#section-3)

jwt-cpp could be expanded to support these as well

**Comment by Thalhammer** [comment]
Looking at the spec ES256K is probably identical to ES256, but uses a different curve.
EdDSA seems to be supported by OpenSSL as well so implementing both of them should not be a big deal.

That being said, I dont think its a high priority, unless there is actually someone that needs it.

**Comment by prince-chrismc** [comment]
:100: Just an easy way to track which one's are missing

**Comment by Sp3EdeR** [comment]
hi everyone, first actual person that needs it reporting in. o/
I will attempt to integrate EdDSA support, probably next week. :)

**Comment by Thalhammer** [comment]
But make sure to base it on the new error_code structure which gets merged in #86 probably this afternoon.

**Comment by Sp3EdeR** [comment]
[This PR](https://github.com/Thalhammer/jwt-cpp/pull/95) could be linked to this issue perhaps.

**Comment by Thalhammer** [comment]
I think we already support ES256K, just not explicitly. As far as I can tell ES256K is identical to ES256 but with a different curve.
However OpenSSL decides the curve based on the loaded key and we don't verify which on it is (which IMHO we probably should).
So if you pass a key with curve secp256k1 and manually set the algorithm header it should work fine.

Going forward we should probably start checking the curve type inside ecdsa to make sure the matched key curve matches what the user thought. Then we add a subclass of ecdsa that specifies a different name and curve and we should be done.
