### ISSUE TITLE
Fix inconsistent usage of set_*_claim / Add missing overloads to set_*_claim

### ISSUE THREAD

**Issue by nicraMarcin** [Thalhammer/jwt-cpp#87]
Hi,
I start using your library and a I have problem with insert bool values and list as array.
`.set_payload_claim("isActive", jwt::claim(user->isActive))` won't compile. `user->isActive` returns boolean.

second, I have list of roles and I don't know, I can't find it in examples how to create array in payload. Could you give any example?
I want in payload as result:
```
...
 roles: [
    "ADMIN",
    "USER"
]
...
```

**Comment by prince-chrismc** [comment]
> I start using your library and a I have problem with insert bool

That is a very valid issue, if you are using the default picojson support, you can do
```diff
-.set_payload_claim("isActive", jwt::claim(user->isActive))
+.set_payload_claim("isActive", jwt::claim(picojson::value(user->isActive)))
```
By wrapping it in a `picojson::value` you can add complex types.

For the "list of strings", we have a claim set, which is an array of string, that's used for known claims like `aud`
```cpp
jwt::claim::set_t roles{ "admin", "user" };
//...
.set_payload_claim("roles", jwt::claim(roles))
```

**Comment by Thalhammer** [comment]
I think instead of adding examples on how to do it (not saying examples are bad!), we should instead make it intuitive to use and fix the underlying issue.

This is easy to do, as we really only need to add the missing overloads.

**Comment by prince-chrismc** [comment]
It's not the jwt-cpp API it's the picojson API, the resolution becomes ambiguous. I tried with nlohmann and it worked
