### ISSUE TITLE
Use the es256 verification program to verify that some invalid jwt-token results are passed

### ISSUE THREAD

**Issue by zerogeass** [Thalhammer/jwt-cpp#97]
env:
os:Ubuntu 16.04.6 LTS
openssl version:OpenSSL 1.0.2g  1 Mar 2016
Programming language：c++

description:
   I verified that jwt-token is illegal on this webpage https://jwt.io/, but the result obtained by using the jwt-cpp library to establish the es256 validator is passed.
   And the jwt-token generated by jwt::create will also have invalid tokens.
 
1.generate jwt token code:
```cpp
std::string jwt_token = jwt::create()
                                    .set_algorithm("ES256")
                                    .set_key_id(op.key_id())
                                    .set_issuer(op.team_id())
                                    .set_issued_at(std::chrono::system_clock::now())
                                    .set_expires_at(std::chrono::system_clock::now() +
                                                    std::chrono::seconds {TOKEN_EXPIRE})
                                    .set_audience(op.aud())
                                    .set_subject(op.apple_id())
                                    .sign(jwt::algorithm::es256 {"", pri_key, "", ""});
```
2.verify jwt token coce:
```cpp
auto decoded_jwt = jwt::decode(token);
    auto verifier    = jwt::verify()
                        .allow_algorithm(jwt::algorithm::es256 {"", private_key, "", ""})
                        .with_issuer(iss)
                        .with_subject(sub);
    try {
        verifier.verify(decoded_jwt);
    } catch (std::exception& e) {
        LOG(DEBUG) << e.what() << ",error token:" << token;
        return false;
    }
```

question:
  Is my usage correct? Or where is the problem? Thanks

**Comment by prince-chrismc** [comment]
With JWT.io, can you  share the test you had done? This will help us check to see if there's an issue

My only concern with your code is the verification. With asymmetric keys you should be using the private key to sign and the public key to verify.

**Comment by Thalhammer** [comment]
Normally you would only pass the public key on verify but given that the private key contains a copy of the public parts it is fine as long as everything is serverside.

When creating a token you dont need to (and should not) set the algorithm name, as the library will do that automatically based on the algorithm passed to `sign`.

Can you share a token + public/private key that demonstrates you problem ?
Maybe generate a new private key if (for obvious reasons) you dont wanna share the exact one used.

**Comment by zerogeass** [comment]
> Normally you would only pass the public key on verify but given that the private key contains a copy of the public parts it is fine as long as everything is serverside.
> 
> When creating a token you dont need to (and should not) set the algorithm name, as the library will do that automatically based on the algorithm passed to `sign`.
> 
> Can you share a token + public/private key that demonstrates you problem ?
> Maybe generate a new private key if (for obvious reasons) you dont wanna share the exact one used.
But i dont use the lastest version to generate token. And i can’t tell you the private key because of the contract. The issue is that I use the v3.0.1 version to generate the wrong token, but it is correct through verifior (the latest version is also correct), but it is illegal on jwt.io. The invalid token like that
eyJhbGciOiJFUzI1NiIsImtpZCI6IjdHRlI3Njg3MzcifQ.eyJhdWQiOiJodHRwczpcL1wvYXBwbGVpZC5hcHBsZS5jb20iLCJleHAiOjE1OTY1NDIzNzAsImlhdCI6MTU5NjQ5OTE3MCwiaXNzIjoiOTJMWUZZMjhaQSIsInN1YiI6InNnLmJpZ28ubGl2ZSJ9.NhbuUNBD-GPPuh8yjs58OYzUSGWQ7aGJX577k2XHFE4III3FJw58eW8o36SgruzP5lDBbM40kWfzjVnckQSB
And the length of the signature part of the token is 2 bits less than that of the normal token

B.Generate invalid token:
`std::string load_key(const std::string& key_path)
{
  std::ifstream input_stream(key_path, std::ios::in);
  std::istreambuf_iterator<char> input_begin(input_stream), input_end;
  std::string private_key(input_begin, input_end);
  input_stream.close();
  return private_key;
}
int main()
{
for(int i = 0 ; i <= 10000; i++){
  std::string private_key = load_key("ecc-private-key.pem");
  std::string token = jwt::create().set_algorithm("ES256")
                                    .set_key_id("839Gk321ET")
                                    .set_issuer("9Fku422irp")
                                    .set_issued_at(std::chrono::system_clock::now())
                                    .set_expires_at(std::chrono::system_clock::now() +
                                                    std::chrono::seconds {3600})
                                    .set_audience("https://appleid.apple.com")
                                    .set_subject("test.jwt")
                                    .sign(jwt::algorithm::es256 {"", private_key, "", ""});
  //std::cout << token << std::endl;
  auto decoded_jwt = jwt::decode(token);
  auto verifier    = jwt::verify().allow_algorithm(jwt::algorithm::es256 {"", private_key, "", ""});
 try {
        verifier.verify(decoded_jwt);
    } catch (std::exception& e) {
   std::cout << token << std::endl; 
   std::cout << e.what() << std::endl;
 } 
}
 return 0;
}`

**Comment by Thalhammer** [comment]
Ahh now we are getting somewhere. There was a bug in the way we concatenated the signature in some older versions. You should upgrade.

**Comment by prince-chrismc** [comment]
Issue was previously report and fixed in master
